import type { LocationId } from '../types';
import type { TaskDef } from './types';

const TUIN_PARK: LocationId[] = ['tuin', 'park'];
const ALLE_NIVEAUS = ['makkelijk', 'normaal', 'pittig'] as const;

/**
 * Extra opdrachten voor de tuin en de speeltuin/het park.
 * Sabotagetips zijn altijd stiekem en veilig: nooit duwen, trekken,
 * iets kapotmaken of iemand pijn doen. Niets nat, vies of met vuur.
 */
export const TASKS_TUIN: TaskDef[] = [
  // ─────────────── Zoeken ───────────────
  {
    id: 't-bladerenladder',
    title: 'De bladerenladder',
    emoji: '🍁',
    category: 'zoeken',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Zoek samen {aantal} bladeren die al op de grond liggen, elk van een andere boom of struik. Leg ze daarna op een rij, van het kleinste naar het grootste blad. Twee keer dezelfde soort? Dan telt er maar één!',
    vars: { aantal: { makkelijk: [5], normaal: [8], pittig: [11] } },
    scoring: { type: 'aantal', target: '{aantal}', unit: 'bladeren' },
    sabotage: [
      'Leg een blad van een soort die er al ligt erbij en zeg dat het "echt een andere" is.',
      'Wissel stiekem twee bladeren van plaats als de rij bijna klaar is.',
      'Zeg dat een mooi groot blad "niet meetelt, want er zit een scheurtje in".',
      'Blijf heel lang onder één en dezelfde struik zoeken.',
    ],
    photo: 'De bladerenladder met alle zoekers erachter.',
  },
  {
    id: 't-drakeneieren',
    title: 'De drakeneieren',
    emoji: '🐉',
    category: 'zoeken',
    locations: TUIN_PARK,
    supplies: ['tennisballen', 'emmers'],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Verstop {aantal} tennisballen (de drakeneieren) in de tuin of in een klein stukje van het park, en zet een emmer als nest bij de start.',
    explain:
      'De draak is haar eieren kwijt! Er liggen {aantal} tennisballen verstopt. Breng ze één voor één naar het nest (de emmer): je mag maar één ei tegelijk dragen, met twee handen. Drie keer mogen jullie aan de spelleider vragen: "Warm of koud?" Blijf altijd in de buurt van de volwassene!',
    vars: { aantal: { makkelijk: [6], normaal: [10], pittig: [14] } },
    scoring: { type: 'aantal', target: '{aantal}', unit: 'eieren' },
    sabotage: [
      'Vind je een ei? Leg het stiekem op een andere, moeilijkere plek.',
      'Verspil een "warm of koud"-vraag op een plek waar jij weet dat er niets ligt.',
      'Draag je ei extra traag en maak een omweg naar het nest.',
      'Roep "Daar heb ik al gekeken!" bij een plek die je niet bekeken hebt.',
    ],
    dilemma: true,
    photo: 'Iedereen rond het nest met de geredde eieren.',
  },
  {
    id: 't-vormenjacht',
    title: 'Windy’s vormenjacht',
    emoji: '🔷',
    category: 'zoeken',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Windy is gek op vormen! Zoek in de tuin of de speeltuin iets bij elke vorm van de lijst. Wijs het aan en roep het luid, dan vinkt de spelleider het af. Niets afbreken, en blijf in de buurt van de volwassene.',
    list: {
      title: 'Zoek iets dat...',
      items: {
        makkelijk: ['rond is', 'vierkant is', 'een driehoek is', 'lang en dun is', 'een streep heeft', 'een gat heeft', 'plat is', 'puntig is', 'op een bal lijkt', 'op een letter lijkt'],
        normaal: ['rond is', 'vierkant is', 'een driehoek is', 'een spiraal heeft', 'een hartvorm heeft', 'op een ster lijkt', 'een kruis maakt', 'een gat heeft', 'op de letter Y lijkt', 'een zigzag heeft', 'een boog maakt'],
        pittig: ['een perfecte cirkel is', 'ovaal is', 'een spiraal heeft', 'een hartvorm heeft', 'op de letter K lijkt', 'een zigzag heeft', 'een ruit is', 'symmetrisch is (links = rechts)', 'een vijfhoek is', 'een zeshoek is', 'een halve maan is'],
      },
      pick: 7,
      secret: false,
    },
    scoring: { type: 'aantal', target: 7, unit: 'vormen' },
    sabotage: [
      'Wijs iets aan dat bijna de juiste vorm heeft en hou vol dat het klopt.',
      'Blijf luidop twijfelen of iets "wel echt rond genoeg" is.',
      'Stuur de groep naar een hoek waarvan je al weet dat er niets te vinden is.',
    ],
    photo: 'De groep die samen de moeilijkste vorm uitbeeldt.',
  },
  {
    id: 't-kaartenstorm',
    title: 'De kaartenstorm',
    emoji: '🃏',
    category: 'zoeken',
    locations: ['tuin'],
    supplies: ['speelkaarten'],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Neem uit een kaartspel de hartenkaarten van aas tot {hoogste} en verstop ze in de tuin (enkel als het droog is): onder een blad, achter een bloempot, op de rand van de zandbak...',
    explain:
      'Oei, een windvlaag heeft de kaarten van Windy door de tuin geblazen! Zoek alle hartenkaarten van aas tot {hoogste} en leg ze op volgorde op een rij. Pas als de rij compleet is, zijn jullie klaar.',
    vars: {
      hoogste: { makkelijk: ['6'], normaal: ['10'], pittig: ['de heer'] },
      aantal: { makkelijk: [6], normaal: [10], pittig: [13] },
    },
    scoring: { type: 'aantal', target: '{aantal}', unit: 'kaarten' },
    sabotage: [
      'Vind je een kaart? Schuif ze stiekem onder een blad en zoek verder.',
      'Leg twee kaarten in de rij verkeerd om.',
      'Zeg dat de 7 er al ligt, ook al is dat niet zo.',
    ],
    photo: 'De volledige kaartenrij met de speurders.',
  },
  {
    id: 't-voeljacht',
    title: 'De voelzoektocht',
    emoji: '🖐️',
    category: 'zoeken',
    locations: TUIN_PARK,
    supplies: ['handdoeken'],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Leg een handdoek klaar als verzamelplek.',
    explain:
      'Zoek dingen die al op de grond liggen en die aanvoelen zoals op de lijst. Leg alles op de handdoek. Niets afbreken of plukken: enkel wat los ligt! Op het einde voelt de spelleider of alles klopt.',
    list: {
      title: 'Zoek iets dat voelt...',
      items: {
        makkelijk: ['zacht', 'ruw', 'glad', 'hard', 'licht als een veertje', 'koel', 'kriebelig', 'bobbelig', 'droog en knisperig'],
        normaal: ['zacht als een knuffel', 'ruw als schuurpapier', 'glad als een knikker', 'knisperend', 'veerkrachtig', 'met ribbels', 'hol vanbinnen', 'donzig', 'zwaarder dan het eruitziet', 'puntig maar niet scherp'],
        pittig: ['glad aan de ene kant en ruw aan de andere', 'zacht maar toch stevig', 'met minstens drie bobbels', 'lichter dan een blad papier', 'koud, ook in de zon', 'met een groef of een streep', 'buigzaam zonder te breken', 'met een gaatje erin', 'ruw én rond', 'harig of pluizig'],
      },
      pick: 6,
      secret: false,
    },
    scoring: { type: 'aantal', target: 6, unit: 'dingen' },
    sabotage: [
      'Leg iets op de handdoek dat net niet goed voelt en zeg dat het perfect is.',
      'Neem stiekem een ding van de handdoek mee "om het nog eens te voelen".',
      'Zeg van een goed ding dat het "eigenlijk eerder glad dan ruw" is.',
    ],
    photo: 'De handdoek vol voelschatten.',
  },
  {
    id: 't-speeltuinbingo',
    title: 'Speeltuinbingo',
    emoji: '🛝',
    category: 'zoeken',
    locations: ['park'],
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    timer: 360,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Speeltuinbingo! Zoek alles van de bingokaart in de speeltuin of het park. Wijs het aan en roep "BINGO!" per vakje. Niet op hoge dingen klimmen, en blijf altijd in de buurt van de volwassene.',
    list: {
      title: 'Bingokaart',
      items: {
        makkelijk: ['een schommel', 'een glijbaan', 'een bank', 'een vuilbak', 'een boom', 'iets roods', 'iets blauws', 'een vogel', 'een fiets', 'een hond (van ver bekijken)', 'een bloem'],
        normaal: ['iets dat draait', 'iets dat wiebelt', 'een bordje met een getal', 'een vuilbak', 'een bank met een leuning', 'iets van touw', 'iets geels', 'een zandbak', 'een hond (van ver bekijken!)', 'een fiets', 'een boom dikker dan jij', 'een wolk die op een dier lijkt'],
        pittig: ['iets dat piept als het beweegt', 'een bordje met een regel erop', 'een bank zonder leuning', 'drie verschillende soorten vogels', 'een wiel', 'een kevertje', 'een bal van iemand anders (niet aankomen!)', 'een plek die half in de zon en half in de schaduw ligt', 'iets met een slot', 'een wegwijzer', 'een boom met een nummerplaatje'],
      },
      pick: 8,
      secret: false,
    },
    scoring: { type: 'aantal', target: 8, unit: 'vakjes' },
    sabotage: [
      'Roep "BINGO!" bij iets dat er maar een beetje op lijkt.',
      'Blijf lang bij één toestel hangen en doe alsof je daar nog iets zoekt.',
      'Zeg dat je iets gezien hebt aan de andere kant, zodat de groep voor niets gaat kijken (maar blijf zelf bij de groep).',
    ],
    photo: 'De hele groep bij het leukste vakje van de kaart.',
  },
  {
    id: 't-natuuralfabet',
    title: 'Het natuuralfabet',
    emoji: '🔤',
    category: 'zoeken',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Zoek voor elke letter van het woord "{woord}" iets dat met die letter begint. Bij KENZO zoek je dus iets met een K, een E, een N, een Z en een O. Leg het op een rij of wijs het aan. Enkel wat op de grond ligt, mag je oprapen!',
    vars: { woord: { makkelijk: ['BOOM', 'ZON', 'BAL'], normaal: ['KENZO', 'WINDY', 'TUINEN'], pittig: ['DUVELKE', 'SPEELTUIN', 'GLIJBAAN'] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Kom af met iets dat met een verkeerde letter begint en zeg het in het Engels, zodat het "toch klopt".',
      'Zeg dat een letter "onmogelijk" is, zodat de groep hem wil overslaan.',
      'Leg jouw ding op de verkeerde plek in de rij.',
    ],
    photo: 'Het woord op een rij, met alle dingen erbij.',
  },

  // ─────────────── Raadsels ───────────────
  {
    id: 't-krijtcode',
    title: 'De krijtcode',
    emoji: '🔢',
    category: 'raadsels',
    locations: TUIN_PARK,
    supplies: ['stoepkrijt'],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Kijk stiekem naar het geheime woord op de tablet en schrijf enkel de cijfercode met stoepkrijt op het terras of een pad.',
    explain:
      'Windy heeft een geheim woord in cijfers op de grond gekrabbeld. Elk cijfer is een letter: 1 = A, 2 = B, 3 = C, en zo verder. Ontcijfer het woord en fluister het in het oor van de spelleider!',
    list: {
      title: 'Geheim woord en code (enkel voor de spelleider)',
      items: {
        makkelijk: ['BAL = 2-1-12', 'BOOM = 2-15-15-13', 'KAT = 11-1-20', 'ZON = 26-15-14', 'VIS = 22-9-19'],
        normaal: ['WINDY = 23-9-14-4-25', 'KENZO = 11-5-14-26-15', 'SCHAT = 19-3-8-1-20', 'TAART = 20-1-1-18-20', 'FEEST = 6-5-5-19-20'],
        pittig: ['SCHOMMEL = 19-3-8-15-13-13-5-12', 'GLIJBAAN = 7-12-9-10-2-1-1-14', 'DUVELKE = 4-21-22-5-12-11-5', 'VERJAARDAG = 22-5-18-10-1-1-18-4-1-7', 'SPEELTUIN = 19-16-5-5-12-20-21-9-14'],
      },
      pick: 1,
      secret: true,
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Tel "per ongeluk" één letter te ver in het alfabet.',
      'Roep heel zeker een woord dat bijna klopt.',
      'Stel voor om te beginnen tellen bij 0 in plaats van bij 1.',
    ],
    dilemma: true,
    photo: 'De ontcijferaars naast de krijtcode.',
  },
  {
    id: 't-raad-en-tik',
    title: 'Raad het en tik het aan',
    emoji: '🌳',
    category: 'raadsels',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    timer: 360,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De spelleider leest een raadsel voor. Het antwoord is iets dat je hier in de tuin of het park kan vinden. Weten jullie het? Loop er samen naartoe en tik het aan (niet plukken, en in het park altijd in de buurt van de volwassene). Hoeveel raadsels lossen jullie op?',
    list: {
      title: 'Raadsels (antwoorden enkel voor de spelleider)',
      items: {
        makkelijk: [
          'Ik ben groen en kort, en de grasmachine knipt mijn haar. (gras)',
          'Ik volg je overal als de zon schijnt. (je schaduw)',
          'Ik heb een stam, takken en bladeren. (een boom)',
          'Ik ben hard en grijs en ik lig altijd stil. (een steen)',
          'Ik ga heen en weer, en jij zit op mij. (een schommel)',
          'Ik ben blauw of grijs en ik hang boven je hoofd. (de lucht)',
          'Je kan op mij zitten, maar ik ben geen stoel uit huis. (een bank)',
        ],
        normaal: [
          'Ik heb bladeren, maar ik ben geen boek. (een boom of struik)',
          'Ik ben er als de zon schijnt, maar als je op mij staat, voel je niets. (een schaduw)',
          'Kinderen glijden van mij af, maar ik ben geen ijsbaan. (een glijbaan)',
          'Ik heb een deur maar geen huis, en ik hou honden buiten of binnen. (een hek of poortje)',
          'Ik eet afval, maar ik word er nooit dik van. (een vuilbak)',
          'Ik hing vroeger hoog, maar nu lig ik op de grond. (een afgevallen blad of takje)',
          'Ik heb korrels maar ik ben geen brood, en je bouwt kastelen met mij. (zand of de zandbak)',
        ],
        pittig: [
          'Hoe feller de zon, hoe donkerder ik word. (een schaduw)',
          'Ik heb ringen, maar geen vingers. (een boomstam of boomstronk)',
          'In de lente ben ik groen, in de herfst bruin en in de winter lig ik op de grond. (een blad)',
          'Mijn benen zijn van metaal, mijn rug van hout, en toch ben ik nooit moe. (een bank)',
          'Ik word gebouwd door vogels, zonder handen. (een nest: enkel aanwijzen!)',
          'Ik ga op en neer, maar ik kom nooit ergens aan. (een wip of schommel)',
          'Je ziet me niet, maar de bladeren dansen als ik kom. (de wind: wijs een bewegend blad aan)',
        ],
      },
      pick: 4,
      secret: true,
    },
    scoring: { type: 'aantal', target: 4, unit: 'raadsels' },
    sabotage: [
      'Loop heel enthousiast naar het verkeerde ding.',
      'Zeg het juiste antwoord heel zacht en een fout antwoord heel luid.',
      'Blijf twijfelen tot de tijd bijna op is.',
    ],
  },
  {
    id: 't-boer-wolf-geit',
    title: 'De boer, de wolf en de geit',
    emoji: '🐐',
    category: 'raadsels',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 4,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Markeer met twee lijnen (takjes, schoenen of jassen) een rivier van een paar stappen breed.',
    explain:
      'Een boer moet een wolf, een geit en een kool over de rivier brengen. In het bootje past enkel de boer plus één passagier. Maar let op: blijft de wolf alleen met de geit, dan eet hij de geit op. Blijft de geit alleen met de kool, dan eet de geit de kool op! Speel het na en breng iedereen veilig over in hoogstens {overtochten} overtochten. De rest zijn raadgevers.',
    vars: { overtochten: { makkelijk: [11], normaal: [9], pittig: [7] } },
    roles: [
      { name: 'Boer', count: 1, hint: 'Jij roeit het bootje: bij elke overtocht ga jij mee.' },
      { name: 'Wolf', count: 1, hint: 'Grom een beetje en wacht op de boer.' },
      { name: 'Geit', count: 1, hint: 'Mèèèh! Jij bent in gevaar.' },
      { name: 'Kool', count: 1, hint: 'Jij mag niets zeggen, want je bent een kool.' },
    ],
    scoring: { type: 'gelukt' },
    sabotage: [
      'Stel heel overtuigd een oversteek voor waarbij de geit alleen blijft met de wolf of de kool.',
      'Tel het aantal overtochten "per ongeluk" verkeerd.',
      'Zeg dat de boer "zeker niemand" mag terugbrengen (dat mag wel!).',
      'Stel als raadgever drie keer dezelfde vraag, zodat de groep in de war raakt.',
    ],
    dilemma: true,
    photo: 'De boer, de wolf, de geit en de kool veilig aan de overkant.',
  },
  {
    id: 't-ja-nee-tuin',
    title: 'Ja of nee in de tuin',
    emoji: '❔',
    category: 'raadsels',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De spelleider denkt aan iets dat je hier kan zien of horen. Jullie mogen samen hoogstens {vragen} vragen stellen waarop de spelleider enkel "ja" of "nee" antwoordt. Raden jullie het voor de vragen op zijn? We spelen 3 rondes.',
    vars: { vragen: { makkelijk: [20], normaal: [15], pittig: [10] } },
    list: {
      title: 'Geheime dingen (sla over wat hier niet is)',
      items: {
        makkelijk: ['een boom', 'de schommel', 'een bank', 'de lucht', 'een steen', 'een vogel', 'het gras', 'een bloem'],
        normaal: ['een wolk', 'de vuilbak', 'een mier', 'een schaduw', 'het tuinhek', 'een dennenappel', 'de zandbak', 'een afgevallen blad'],
        pittig: ['een regenworm (ergens onder de grond)', 'de wind', 'een spinnenweb', 'de zon', 'een voetafdruk', 'een vogelnest', 'mos', 'de wortels van een boom'],
      },
      pick: 3,
      secret: true,
    },
    scoring: { type: 'aantal', target: 3, unit: 'dingen geraden' },
    sabotage: [
      'Stel een vraag die al gesteld is.',
      'Roep heel snel een gok, zodat er een vraag verloren gaat.',
      'Stel vragen over iets totaal anders, zoals "Is het een olifant?".',
    ],
  },

  // ─────────────── Samenwerken ───────────────
  {
    id: 't-touwfiguur',
    title: 'De blinde touwfiguur',
    emoji: '🔺',
    category: 'samenwerken',
    locations: TUIN_PARK,
    supplies: ['lang-touw'],
    minPlayers: 4,
    minutes: 6,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Iedereen neemt het lange touw vast met twee handen en doet de ogen dicht. Maak nu samen met het touw {vorm}, zonder te kijken en zonder los te laten! Denken jullie dat het klaar is? Leg het touw neer en doe de ogen open.',
    vars: {
      vorm: {
        makkelijk: ['een cirkel', 'een vierkant'],
        normaal: ['een driehoek', 'een ruit', 'een rechthoek'],
        pittig: ['een ster', 'een huisje met een dak', 'de letter W', 'een hart'],
      },
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Schuif je stukje touw stiekem een beetje de verkeerde kant op.',
      'Zeg dat jouw hoek "zeker al recht" is.',
      'Stel voor om een andere vorm te maken "omdat dat makkelijker is".',
      'Loer heel even en geef dan net fout advies.',
    ],
    dilemma: true,
    photo: 'De touwfiguur met alle blinde bouwers erbij.',
  },
  {
    id: 't-vliegend-dienblad',
    title: 'Het vliegende dienblad',
    emoji: '🥏',
    category: 'samenwerken',
    locations: TUIN_PARK,
    supplies: ['frisbee', 'tennisballen', 'pionnen'],
    minPlayers: 3,
    minutes: 6,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Zet een pion als keerpunt op {afstand} grote stappen van de start.',
    explain:
      'Leg de frisbee omgekeerd, met {ballen} tennisballen erop. De hele groep draagt de frisbee samen naar de pion en terug, maar iedereen mag hem maar met één vinger aanraken! Valt er een bal? Dan begin je opnieuw aan de start.',
    vars: { ballen: { makkelijk: [1], normaal: [2], pittig: [3] }, afstand: { makkelijk: [8], normaal: [10], pittig: [12] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Laat je vinger net iets zakken, zodat de frisbee scheef hangt.',
      'Wandel net iets sneller of trager dan de rest.',
      'Roep "stop!" net op het moment dat het goed loopt.',
    ],
    photo: 'Het dienblad onderweg, met alle vingers eronder.',
  },
  {
    id: 't-buikbalrups',
    title: 'De buikbalrups',
    emoji: '🐛',
    category: 'samenwerken',
    locations: TUIN_PARK,
    supplies: ['tennisballen', 'pionnen'],
    minPlayers: 3,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Zet een pion op {afstand} grote stappen van de start.',
    explain:
      'Ga in een rij staan en klem een tennisbal tussen jouw buik en de rug van wie voor je staat. Wandel nu als één grote rups rond de pion en terug. Niemand mag de ballen met de handen aanraken, en niemand duwt! Valt er een bal? Dan moet de rups terug naar de start.',
    vars: { afstand: { makkelijk: [5], normaal: [8], pittig: [10] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Wandel net iets te snel voor wie voor je loopt, maar duw nooit.',
      'Laat je buik een beetje inzakken, zodat de bal wiebelt.',
      'Stel voor om een heel scherpe bocht te nemen.',
    ],
    photo: 'De rups in volle actie.',
  },
  {
    id: 't-lavarivier',
    title: 'De lavarivier',
    emoji: '🌋',
    category: 'samenwerken',
    locations: TUIN_PARK,
    supplies: ['karton'],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Snij karton in stukken zo groot als een schoenendoos (één per speler) en duid een overkant aan op {afstand} grote stappen.',
    explain:
      'Het gras is lava! Steek de rivier over naar de overkant, {afstand} grote stappen verder, met enkel stukken karton als stapstenen. Jullie krijgen {stenen}. Een stuk karton waar niemand op staat of aan raakt, wordt door de lava opgeslokt: de spelleider neemt het weg. Rustig stappen, niet springen, en iedereen moet de overkant halen!',
    vars: {
      afstand: { makkelijk: [8], normaal: [10], pittig: [12] },
      stenen: { makkelijk: ['evenveel stukken als er spelers zijn'], normaal: ['één stuk minder dan er spelers zijn'], pittig: ['twee stukken minder dan er spelers zijn'] },
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Stap net van je karton af als niemand kijkt, zodat de spelleider het mag afpakken.',
      'Laat een stuk karton even los op het moment dat het doorgegeven wordt.',
      'Stel voor om een omweg te maken.',
      'Ga op het stuk karton staan dat de volgende net nodig heeft.',
    ],
    dilemma: true,
    photo: 'Iedereen samen op de laatste stapstenen.',
  },
  {
    id: 't-samen-opstaan',
    title: 'Rug aan rug omhoog',
    emoji: '🙌',
    category: 'samenwerken',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 4,
    minutes: 5,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Ga op het gras zitten met de ruggen tegen elkaar en haak je armen in die van je buren. Sta nu samen recht zonder je handen op de grond te zetten! Tel rustig: "1, 2, 3, hop!" Wie doet mee: {groep}.',
    vars: {
      groep: {
        makkelijk: ['per twee, en elk duo moet het lukken'],
        normaal: ['per drie of vier, en elk groepje moet het lukken'],
        pittig: ['de hele groep tegelijk, in één kring'],
      },
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Zet je voeten net iets te ver naar voren.',
      'Roep "hop!" net een tel te vroeg.',
      'Leun een klein beetje de verkeerde kant op, maar nooit zo dat iemand pijn heeft.',
      'Begin te giechelen op het moment dat iedereen zich moet concentreren.',
    ],
    photo: 'Het moment dat iedereen net rechtkomt.',
  },
  {
    id: 't-lopende-band',
    title: 'De lopende band',
    emoji: '🎾',
    category: 'samenwerken',
    locations: TUIN_PARK,
    supplies: ['tennisballen', 'emmers'],
    minPlayers: 3,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Zet twee emmers {afstand} grote stappen uit elkaar en leg {aantal} tennisballen in de eerste emmer.',
    explain:
      'Breng alle {aantal} tennisballen van de ene emmer naar de andere, {afstand} grote stappen verder. Maar: met een bal in je hand mag je niet stappen! Geef hem door. Wie niets meer door te geven heeft, loopt naar vooraan de rij. Stapt iemand toch met een bal? Dan gaat die bal terug naar de eerste emmer.',
    vars: { aantal: { makkelijk: [5], normaal: [8], pittig: [12] }, afstand: { makkelijk: [10], normaal: [15], pittig: [20] } },
    scoring: { type: 'aantal', target: '{aantal}', unit: 'ballen' },
    sabotage: [
      'Zet "per ongeluk" een klein stapje met de bal in je hand.',
      'Geef de bal door op een moment dat je buur net niet kijkt.',
      'Loop heel traag naar voren als je aan de beurt bent.',
      'Leg de bal naast de emmer in plaats van erin.',
    ],
    dilemma: true,
  },
  {
    id: 't-spinnenweb',
    title: 'Het reuzenspinnenweb',
    emoji: '🕸️',
    category: 'samenwerken',
    locations: TUIN_PARK,
    supplies: ['wol'],
    minPlayers: 3,
    minutes: 10,
    timer: 360,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Span met wol een spinnenweb tussen twee bomen of palen, met één gat per speler plus {extra} extra gaten, allemaal tussen kniehoogte en schouderhoogte. Knoop losjes, zodat de wol meteen lost als iemand blijft haken.',
    explain:
      'Een reuzenspin heeft de weg versperd! Iedereen moet door het web naar de andere kant, zonder de draden te raken. Elk gat mag maar één keer gebruikt worden en niemand wordt opgetild. Raakt iemand een draad? Dan moet die terug en opnieuw proberen.',
    vars: { extra: { makkelijk: [3], normaal: [1], pittig: [0] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Raak "per ongeluk" een draad met je mouw.',
      'Kies een gat dat eigenlijk perfect was voor iemand anders.',
      'Zeg dat je een draad zag bewegen toen iemand er netjes door ging.',
    ],
    dilemma: true,
    photo: 'Iemand halverwege door het spinnenweb.',
  },
  {
    id: 't-knoop-in-het-touw',
    title: 'De onmogelijke knoop',
    emoji: '🪢',
    category: 'samenwerken',
    locations: TUIN_PARK,
    supplies: ['lang-touw'],
    minPlayers: 3,
    minutes: 6,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Iedereen neemt het lange touw vast met twee handen, verspreid over het touw. Leg nu samen {knopen} in het touw, zonder dat iemand loslaat of zijn handen over het touw laat schuiven! Jullie mogen wel stappen, draaien en onder of over het touw gaan.',
    vars: { knopen: { makkelijk: ['één knoop (de twee spelers aan de uiteinden mogen één keer kort loslaten)'], normaal: ['één knoop'], pittig: ['twee knopen'] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Schuif je handen stiekem een klein beetje over het touw.',
      'Stel voor om het touw "gewoon heel even" los te laten.',
      'Stap net de verkeerde kant op als de knoop bijna lukt.',
    ],
    photo: 'De knoop, met iedereen er nog aan vast.',
  },

  // ─────────────── Geheugen ───────────────
  {
    id: 't-natuurtweeling',
    title: 'Zoek de tweeling',
    emoji: '🌰',
    category: 'geheugen',
    locations: TUIN_PARK,
    supplies: ['handdoeken'],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Leg {aantal} natuurdingen die in de tuin of het park op de grond liggen (blad, steentje, takje, dennenappel, veer...) onder een handdoek.',
    explain:
      'Onder de handdoek liggen {aantal} schatten uit de natuur. Jullie mogen 30 seconden kijken, daarna gaat de handdoek er weer over. Zoek nu van elk ding een tweeling in de tuin of het park, enkel wat al op de grond ligt. Hoeveel tweelingen vinden jullie?',
    vars: { aantal: { makkelijk: [6], normaal: [9], pittig: [12] } },
    scoring: { type: 'aantal', target: '{aantal}', unit: 'tweelingen' },
    sabotage: [
      'Kom af met een tweeling die er niet echt op lijkt.',
      'Zeg dat er "zeker ook een eikel" lag, terwijl dat niet zo is.',
      'Blijf zoeken naar iets dat al gevonden is.',
    ],
    photo: 'De originelen naast hun tweelingen.',
  },
  {
    id: 't-geheugenparcours',
    title: 'Het geheugenparcours',
    emoji: '🧭',
    category: 'geheugen',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De spelleider loopt één keer een geheim parcours voor, met {stappen} stappen: bijvoorbeeld "tik de boom aan, hink naar de bank, draai een rondje". Kijk goed! Daarna doet de hele groep het samen na, in precies dezelfde volgorde. Jullie mogen elkaar helpen onthouden.',
    vars: { stappen: { makkelijk: [4], normaal: [6], pittig: [8] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Doe een stap in de verkeerde volgorde en kijk er heel zeker bij.',
      'Voeg een extra stap toe die er niet bij was.',
      'Zeg "nee, het was twee keer hinken!" terwijl het maar één keer was.',
    ],
  },
  {
    id: 't-boemvakjes',
    title: 'De boemvakjes',
    emoji: '💥',
    category: 'geheugen',
    locations: TUIN_PARK,
    supplies: ['stoepkrijt'],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Teken met stoepkrijt op het terras of een pad een rooster van 4 vakjes breed en 5 vakjes lang. Schrijf A, B, C, D boven de kolommen en 1 tot 5 naast de rijen (rij 1 is de start).',
    explain:
      'In het rooster ligt een geheim veilig pad, en enkel de spelleider kent het. Om de beurt stap je vakje per vakje vooruit, opzij of schuin. Stap je op een fout vakje? Dan roept de spelleider "BOEM!" en begint de volgende helemaal opnieuw. Onthoud goed welke vakjes veilig zijn! Doel: {doel} spelers aan de overkant.',
    vars: { doel: { makkelijk: [2], normaal: [3], pittig: [4] } },
    list: {
      title: 'Het veilige pad (enkel voor de spelleider)',
      items: {
        makkelijk: ['B1 → B2 → B3 → C3 → C4 → C5', 'A1 → B2 → B3 → B4 → A5', 'D1 → D2 → C3 → C4 → D5', 'C1 → C2 → B2 → B3 → B4 → B5'],
        normaal: ['A1 → B2 → C2 → C3 → B4 → B5', 'D1 → C1 → C2 → B3 → B4 → C5', 'B1 → A2 → A3 → B4 → C4 → C5', 'C1 → D2 → D3 → C3 → B4 → A5'],
        pittig: ['A1 → A2 → B2 → C2 → D3 → C4 → B4 → B5', 'D1 → C2 → B2 → A3 → A4 → B5', 'B1 → C1 → D2 → C3 → B3 → A4 → A5', 'C1 → B2 → A2 → B3 → C3 → D4 → C5'],
      },
      pick: 1,
      secret: true,
    },
    scoring: { type: 'aantal', target: '{doel}', unit: 'spelers aan de overkant' },
    sabotage: [
      'Wijs "behulpzaam" een fout vakje aan voor wie aan de beurt is.',
      'Zeg dat je zeker weet dat een BOEM-vakje eigenlijk veilig was.',
      'Stap zelf één keer bewust op een vakje waarvan je weet dat het fout is.',
      'Verwar links en rechts als je uitlegt welke vakjes veilig waren.',
    ],
    dilemma: true,
    photo: 'Het rooster met een speler op het laatste vakje.',
  },
  {
    id: 't-tuinwoordenboek',
    title: 'Het tuinwoordenboek',
    emoji: '📖',
    category: 'geheugen',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Verzin samen voor {aantal} dingen uit de tuin een beweging: "boom" = armen omhoog, "steen" = in elkaar kruipen, enzovoort. Daarna roept de spelleider de woorden door elkaar, steeds sneller. Iedereen moet meteen de juiste beweging doen. Lukt het {doel} keer na elkaar zonder dat iemand zich vergist?',
    vars: { aantal: { makkelijk: [4], normaal: [6], pittig: [8] }, doel: { makkelijk: [8], normaal: [12], pittig: [15] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Doe met veel overtuiging de beweging van een ander woord.',
      'Stel een beweging voor die heel erg lijkt op een andere.',
      'Wacht net te lang, zodat je buren beginnen te twijfelen.',
    ],
    photo: 'Iedereen tegelijk in de "boom"-pose.',
  },

  // ─────────────── Behendigheid ───────────────
  {
    id: 't-frisbee-landing',
    title: 'De frisbeelanding',
    emoji: '🛬',
    category: 'behendigheid',
    locations: TUIN_PARK,
    supplies: ['frisbee', 'hoepels'],
    minPlayers: 3,
    minutes: 7,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Leg drie hoepels op het gras: op {kort}, {middel} en {ver} grote stappen van de werplijn. Iedereen gooit om de beurt de frisbee. Landt hij in een hoepel? Dan krijgen jullie 1, 2 of 3 punten: hoe verder, hoe meer. Samen moeten jullie {doel} punten halen in 3 rondes.',
    vars: {
      kort: { makkelijk: [3], normaal: [4], pittig: [5] },
      middel: { makkelijk: [5], normaal: [7], pittig: [8] },
      ver: { makkelijk: [7], normaal: [9], pittig: [11] },
      doel: { makkelijk: [5], normaal: [8], pittig: [10] },
    },
    scoring: { type: 'aantal', target: '{doel}', unit: 'punten' },
    sabotage: [
      'Gooi net over de hoepel heen.',
      'Geef mikadvies over "de wind" dat helemaal niet klopt.',
      'Schuif een hoepel stiekem een halve stap verder als je de frisbee gaat halen.',
    ],
    photo: 'De frisbee in volle vlucht.',
  },
  {
    id: 't-omgekeerd-bowlen',
    title: 'Omgekeerd bowlen',
    emoji: '🎳',
    category: 'behendigheid',
    locations: TUIN_PARK,
    supplies: ['bal', 'pionnen'],
    minPlayers: 3,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Zet {pionnen} pionnen als kegels op {afstand} grote stappen. Iedereen rolt om de beurt de bal, maar achterstevoren: met je rug naar de kegels, tussen je benen door! Omgevallen kegels blijven liggen. Gooien jullie samen alles om in hoogstens {worpen} worpen?',
    vars: {
      pionnen: { makkelijk: [3], normaal: [5], pittig: [6] },
      afstand: { makkelijk: [4], normaal: [5], pittig: [6] },
      worpen: { makkelijk: [10], normaal: [8], pittig: [6] },
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Rol de bal net iets te hard, zodat hij naast de kegels vliegt.',
      'Geef als "coach" het advies om meer naar links te mikken als het naar rechts moet.',
      'Tel de worpen luidop verkeerd, zodat de groep denkt dat er meer over zijn.',
    ],
    photo: 'Iemand die door de benen mikt.',
  },
  {
    id: 't-koorddanser',
    title: 'De koorddansers',
    emoji: '🎪',
    category: 'behendigheid',
    locations: TUIN_PARK,
    supplies: ['lang-touw', 'knuffels'],
    minPlayers: 3,
    minutes: 6,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Leg het lange touw in bochten op het gras: dat is het koord boven het ravijn! Om de beurt wandel je over het touw, hiel tegen teen, met een knuffel op je hoofd. {extra} Valt de knuffel of stap je naast het touw? Dan begin je opnieuw. Halen jullie het allemaal voor de tijd om is?',
    vars: {
      extra: {
        makkelijk: ['Je mag je armen gebruiken om in evenwicht te blijven.'],
        normaal: ['Halverwege moet je stilstaan en tot drie tellen.'],
        pittig: ['Halverwege moet je een rondje draaien op het touw.'],
      },
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Leg het touw "om te helpen" nog wat bochtiger.',
      'Zeg "voorzichtig!" net op het moment dat iemand in evenwicht is.',
      'Leg de knuffel net iets scheef op het hoofd van de volgende.',
    ],
    photo: 'Een koorddanser met de knuffel op het hoofd.',
  },
  {
    id: 't-voetgolf',
    title: 'Voetgolf',
    emoji: '⛳',
    category: 'behendigheid',
    locations: TUIN_PARK,
    supplies: ['bal', 'pionnen'],
    minPlayers: 3,
    minutes: 8,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Zet {poortjes} poortjes van telkens twee pionnen, een paar grote stappen uit elkaar, en nummer ze in je hoofd.',
    explain:
      'De hele groep speelt samen één golfbal! Om de beurt trap je de bal één keer, zachtjes. De bal moet door alle {poortjes} poortjes, in de juiste volgorde. Lukt het met hoogstens {trappen} trappen?',
    vars: { poortjes: { makkelijk: [3], normaal: [4], pittig: [5] }, trappen: { makkelijk: [12], normaal: [14], pittig: [15] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Trap net iets te hard, zodat de bal voorbij het poortje rolt.',
      'Tel de trappen luidop verkeerd.',
      'Stel een "slimme" route voor die eigenlijk langer is.',
    ],
  },
  {
    id: 't-stenenmannetje',
    title: 'Het stenenmannetje',
    emoji: '🪨',
    category: 'behendigheid',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Bouw samen een toren van {stenen} losse steentjes die op de grond liggen (geen steentjes? Neem stukjes schors of dikke takjes). De toren moet 10 tellen blijven staan zonder dat iemand hem aanraakt. Om de beurt legt iemand er één op, en daarna leggen jullie alles netjes terug!',
    vars: { stenen: { makkelijk: [4], normaal: [6], pittig: [8] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Kies een ronde, wiebelige steen voor jouw beurt.',
      'Adem heel diep uit vlak naast de toren (maar raak hem niet aan!).',
      'Stel voor om de grootste steen bovenaan te leggen.',
    ],
    photo: 'Het stenenmannetje met de bouwers.',
  },
  {
    id: 't-touwlimbo',
    title: 'Springtouwlimbo',
    emoji: '🕺',
    category: 'behendigheid',
    locations: TUIN_PARK,
    supplies: ['springtouw'],
    minPlayers: 4,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Twee Touwhouders houden het springtouw strak, eerst op schouderhoogte. Iedereen gaat er om de beurt onderdoor, achterover leunend, zonder het touw te raken en zonder je handen op de grond te zetten. Lukt het iedereen? Dan zakt het touw een hand lager en wisselen de Touwhouders. Halen jullie {niveaus} niveaus?',
    vars: { niveaus: { makkelijk: [3], normaal: [4], pittig: [5] } },
    roles: [{ name: 'Touwhouder', count: 2, hint: 'Hou het touw strak en stil, en laat meteen los als iemand valt.' }],
    scoring: { type: 'aantal', target: '{niveaus}', unit: 'niveaus' },
    sabotage: [
      'Als Touwhouder: hou het touw een klein beetje lager dan afgesproken.',
      'Raak het touw "per ongeluk" met je neus of je haar.',
      'Maak iemand aan het lachen net als die onder het touw gaat.',
    ],
    dilemma: true,
    photo: 'Iemand die heel diep onder het touw door gaat.',
  },
  {
    id: 't-bladerblazers',
    title: 'De bladerblazers',
    emoji: '🍃',
    category: 'behendigheid',
    locations: TUIN_PARK,
    supplies: ['rietjes'],
    minPlayers: 3,
    minutes: 6,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Leg een droog blaadje van de grond op het terras of een pad, op een plek uit de wind. Iedereen krijgt een eigen rietje. Om de beurt blaas je drie keer door je rietje tegen het blaadje, zonder het aan te raken, en dan is de volgende. Komt het blaadje over de finish, {afstand} grote stappen verder, voor de tijd om is?',
    vars: { afstand: { makkelijk: [3], normaal: [5], pittig: [7] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Blaas net schuin, zodat het blaadje van het pad af waait.',
      'Tel je drie keer blazen heel traag.',
      'Adem stiekem in in plaats van uit, dan gebeurt er niets.',
    ],
    photo: 'Alle bladerblazers op hun knieën bij het blaadje.',
  },
  {
    id: 't-knikkerschijf',
    title: 'De knikkerschijf',
    emoji: '🎯',
    category: 'behendigheid',
    locations: TUIN_PARK,
    supplies: ['knikkers', 'stoepkrijt'],
    minPlayers: 3,
    minutes: 7,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Teken met stoepkrijt op het terras of een pad een schietschijf met drie ringen: de binnenste is 3 punten, de middelste 2 en de buitenste 1. Iedereen rolt twee knikkers vanaf een lijn op {afstand} voeten. Waar een knikker stil blijft liggen, tellen de punten. Samen moeten jullie {doel} punten halen!',
    vars: { afstand: { makkelijk: [6], normaal: [8], pittig: [10] }, doel: { makkelijk: [5], normaal: [8], pittig: [11] } },
    scoring: { type: 'aantal', target: '{doel}', unit: 'punten' },
    sabotage: [
      'Rol je knikker net iets te hard.',
      'Tik "per ongeluk" een goede knikker weg met die van jou.',
      'Geef het advies om "lekker hard" te rollen.',
    ],
    photo: 'De schietschijf vol knikkers.',
  },

  // ─────────────── Creatief ───────────────
  {
    id: 't-fabeldier',
    title: 'Het fabeldier van de tuin',
    emoji: '🦄',
    category: 'creatief',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 10,
    timer: 420,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Maak samen op de grond een verzonnen dier met enkel dingen die al op de grond liggen: takjes, bladeren, steentjes, dennenappels. Het dier moet {kenmerken} hebben. Daarna geven jullie het een naam en een geluid, en vertellen jullie aan Windy wat het graag eet.',
    vars: {
      kenmerken: {
        makkelijk: ['vier poten en een staart'],
        normaal: ['zes poten, vleugels en een staart'],
        pittig: ['drie koppen, acht poten, vleugels en een stekelstaart'],
      },
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Vergeet stiekem één van de verplichte kenmerken.',
      'Stel een naam voor die niemand kan uitspreken.',
      'Leg een onderdeel net op de verkeerde plek.',
    ],
    photo: 'Het fabeldier met zijn makers, die allemaal zijn geluid maken.',
  },
  {
    id: 't-tuinorkest',
    title: 'Het tuinorkest',
    emoji: '🥁',
    category: 'creatief',
    locations: TUIN_PARK,
    supplies: ['emmers'],
    minPlayers: 3,
    minutes: 9,
    timer: 360,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Maak muziek met de tuin: trommel zachtjes op een omgekeerde emmer, tik twee steentjes tegen elkaar, ritsel met droge bladeren. Verzin samen een lied van {regels} zinnen over {onderwerp} en speel het voor de spelleider. Iedereen speelt mee op een instrument!',
    vars: {
      regels: { makkelijk: [2], normaal: [4], pittig: [6] },
      onderwerp: { normaal: ['’t Duvelke dat zich verstopt', 'Windy haar verdwenen pruik', 'onzen Kenzo in de speeltuin', 'de jarige', 'een egel die verdwaald is'] },
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Speel steeds net uit de maat.',
      'Vergeet je zin als het jouw beurt is.',
      'Kies een instrument dat bijna geen geluid maakt.',
    ],
    photo: 'Het volledige orkest met zijn instrumenten.',
  },
  {
    id: 't-krijtparcours',
    title: 'Het krijtparcours',
    emoji: '🌀',
    category: 'creatief',
    locations: TUIN_PARK,
    supplies: ['stoepkrijt'],
    minPlayers: 3,
    minutes: 12,
    timer: 480,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Ontwerp samen met stoepkrijt op het terras of een pad een hinkel- en springparcours met {stations} stations: een spiraal, zigzaglijnen, hinkelvakjes, een plek om een rondje te draaien... Schrijf of teken bij elk station wat je moet doen. Als het klaar is, moet iedereen het parcours één keer foutloos afleggen!',
    vars: { stations: { makkelijk: [4], normaal: [6], pittig: [8] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Teken een station dat net iets te moeilijk is.',
      'Maak de uitleg bij jouw station onduidelijk.',
      'Treuzel heel lang bij het tekenen van jouw stuk.',
    ],
    photo: 'Het hele parcours van bovenaf.',
  },
  {
    id: 't-knuffelnest',
    title: 'Een nest voor Kenzo’s knuffel',
    emoji: '🪺',
    category: 'creatief',
    locations: TUIN_PARK,
    supplies: ['knuffels'],
    minPlayers: 3,
    minutes: 10,
    timer: 420,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Onzen Kenzo heeft een knuffel die een nest nodig heeft! Bouw samen een nest met enkel wat al op de grond ligt: takjes, bladeren, gemaaid gras. Het nest moet minstens zo groot zijn als twee handen. Test: de knuffel moet erin blijven liggen terwijl de spelleider tot {tellen} telt en zachtjes op het nest blaast.',
    vars: { tellen: { makkelijk: [5], normaal: [10], pittig: [15] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Leg een takje zo dat het nest scheef wordt.',
      'Stel voor om enkel grote, stijve takken te gebruiken.',
      'Blijf heel lang zoeken naar "het perfecte blaadje".',
    ],
    photo: 'De knuffel in zijn nieuwe nest.',
  },

  // ─────────────── Quiz ───────────────
  {
    id: 't-waar-of-windypraat',
    title: 'Waar of Windy-praat?',
    emoji: '🌲',
    category: 'quiz',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Kies twee bomen of palen in de buurt: de ene is "WAAR", de andere is "WINDY-PRAAT".',
    explain:
      'Windy vertelt dingen over de natuur, maar ze verzint er ook een paar! Na elke zin overleggen jullie en lopen jullie samen naar de boom van "WAAR" of de boom van "WINDY-PRAAT". Iedereen moet bij dezelfde boom staan. Hoeveel keer kiezen jullie juist?',
    list: {
      title: 'Zinnen (antwoorden enkel voor de spelleider)',
      items: {
        makkelijk: [
          'Een spin heeft acht poten. (waar)',
          'Egels drinken graag melk. (Windy-praat: daar worden ze ziek van, ze drinken water)',
          'Een eikel groeit aan een eik. (waar)',
          'Een lieveheersbeestje heeft altijd zeven stippen. (Windy-praat: er zijn er met 2, 10 of zelfs 22 stippen)',
          'Rupsen worden vlinders. (waar)',
          'Vogels hebben tanden. (Windy-praat)',
          'Een regenworm heeft geen poten. (waar)',
          'Een eekhoorn verstopt nootjes voor de winter. (waar)',
          'Koeien kunnen vliegen als ze heel blij zijn. (Windy-praat)',
        ],
        normaal: [
          'Een spin is een insect. (Windy-praat: insecten hebben zes poten, een spin acht)',
          'Vlinders proeven met hun voeten. (waar)',
          'Een slak heeft duizenden piepkleine tandjes. (waar)',
          'Kikkers drinken met hun mond. (Windy-praat: ze nemen water op via hun huid)',
          'Aan de jaarringen in een boomstam kan je zien hoe oud een boom is. (waar)',
          'Een mol is helemaal blind. (Windy-praat: hij ziet slecht, maar wel licht en donker)',
          'Bijen dansen om elkaar de weg naar bloemen te tonen. (waar)',
          'Een merel is een soort kraai. (Windy-praat: het is een lijster)',
          'Uilen kunnen hun ogen niet draaien, daarom draaien ze hun kop. (waar)',
        ],
        pittig: [
          'Krekels horen met hun poten. (waar: hun oren zitten op hun voorpoten)',
          'Een octopus heeft drie harten. (waar)',
          'Vleermuizen zijn blind. (Windy-praat: ze zien wel, en ze gebruiken ook echo’s)',
          'Een goudvis onthoudt maar drie seconden. (Windy-praat: ze onthouden dingen maandenlang)',
          'Een boom drinkt vooral via zijn bladeren. (Windy-praat: via zijn wortels)',
          'Eekhoorns vergeten waar ze sommige nootjes verstopten, en zo groeien er nieuwe bomen. (waar)',
          'Mieren kunnen veel meer dragen dan hun eigen gewicht. (waar)',
          'Een vos is familie van de kat. (Windy-praat: van de hond)',
          'Een regenworm heeft meer dan één hart. (waar: vijf paar hartbogen)',
        ],
      },
      pick: 6,
      secret: true,
    },
    scoring: { type: 'aantal', target: 6, unit: 'juist' },
    sabotage: [
      'Loop heel zeker naar de verkeerde boom, zodat anderen je volgen.',
      'Zeg "dat hebben we op school geleerd" bij een fout antwoord.',
      'Blijf twijfelen tot de spelleider zegt dat jullie moeten kiezen.',
    ],
    dilemma: true,
  },
  {
    id: 't-schatten-maar',
    title: 'Schatten maar!',
    emoji: '📏',
    category: 'quiz',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 9,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De spelleider stelt schatvragen over de tuin of het park. Spreek samen één getal af, en meet of tel het daarna samen na. Zit jullie schatting binnen de marge? Dan telt ze! Doel: {doel} goede schattingen.',
    vars: { doel: { makkelijk: [2], normaal: [3], pittig: [4] } },
    list: {
      title: 'Schatvragen',
      items: {
        normaal: [
          'Hoeveel grote stappen is het van hier tot de verste boom die je ziet? (marge: 3)',
          'Hoeveel seconden duurt het om samen rond het huis of de speeltuin te wandelen? (marge: 15)',
          'Hoeveel kinderen kunnen er naast elkaar op de bank of de rand van het terras zitten? (marge: 1)',
          'Hoeveel keer kan één iemand in 10 seconden in de handen klappen? (marge: 4)',
          'Hoeveel voeten (hiel tegen teen) is de schaduw van de spelleider lang? (marge: 2)',
          'Hoeveel blaadjes liggen er in een kring die je met je armen maakt? (marge: 5)',
          'Hoeveel kikkersprongen heb je nodig om het gras over te steken? (marge: 3)',
          'Hoeveel vogels hoor of zie je als iedereen één minuut stil is? (marge: 2)',
        ],
      },
      pick: 5,
      secret: false,
    },
    scoring: { type: 'aantal', target: '{doel}', unit: 'schattingen' },
    sabotage: [
      'Stel een belachelijk groot of klein getal voor en blijf het verdedigen.',
      'Tel mee bij het natellen, maar tel "per ongeluk" verkeerd.',
      'Zet heel kleine stapjes als je de afstand mag nameten.',
    ],
  },
  {
    id: 't-kenzos-dierengeheim',
    title: 'Kenzo’s dierengeheim',
    emoji: '🦔',
    category: 'quiz',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Onzen Kenzo denkt aan een dier dat je in een tuin of park kan tegenkomen. De spelleider leest één hint voor, en jullie mogen één keer raden. Fout? Dan komt de volgende hint. Raden jullie het binnen drie hints? Dan telt het dier!',
    list: {
      title: 'Dierenhints (antwoord enkel voor de spelleider)',
      items: {
        makkelijk: [
          '1: Ik slaap de hele winter. 2: Ik rol me op als een bal. 3: Ik heb stekels. (egel)',
          '1: Ik ben heel klein en werk hard. 2: Ik woon met duizenden broers en zussen. 3: Je ziet me vaak in een lange rij op de stoep. (mier)',
          '1: Ik heb een lange pluimstaart. 2: Ik klim in bomen. 3: Ik verstop nootjes. (eekhoorn)',
          '1: Ik heb gekleurde vleugels. 2: Ik was eerst een rups. 3: Ik fladder van bloem naar bloem. (vlinder)',
          '1: Ik heb geen poten. 2: Ik woon onder de grond. 3: Na een regenbui kruip ik naar boven. (regenworm)',
          '1: Ik maak honing. 2: Ik zoem. 3: Ik ben geel met zwart. (bij)',
          '1: Ik draag mijn huis mee. 2: Ik ben heel traag. 3: Ik laat een glimmend spoor achter. (slak)',
        ],
        normaal: [
          '1: Ik jaag ’s nachts. 2: Ik kan mijn kop bijna helemaal rond draaien. 3: Oehoe! (uil)',
          '1: Ik heb acht poten. 2: Ik ben geen insect. 3: Ik maak een web. (spin)',
          '1: Het mannetje is zwart met een oranje snavel. 2: Ik zing vroeg in de ochtend. 3: Ik trek wormen uit het gras. (merel)',
          '1: Ik woon onder de grond. 2: Ik heb grote graafpoten. 3: Ik laat bergjes aarde achter in het gras. (mol)',
          '1: Ik ben rood met zwarte stippen. 2: Ik eet bladluizen. 3: Mijn naam heeft iets met de hemel te maken. (lieveheersbeestje)',
          '1: Ik ben een klein vogeltje. 2: Ik heb een oranjerode borst. 3: Je ziet me vaak op kerstkaarten. (roodborstje)',
          '1: Ik kwaak. 2: Ik was eerst een kikkervisje. 3: Ik spring ver met mijn achterpoten. (kikker)',
        ],
        pittig: [
          '1: Ik vlieg ’s nachts. 2: Ik hang ondersteboven als ik slaap. 3: Ik vind mijn weg met echo’s. (vleermuis)',
          '1: Ik eet slakken en kevers. 2: In de herfst zoek ik een hoop bladeren om in te slapen. 3: Ik heb zo’n 5000 stekels. (egel)',
          '1: Ik heb een lange rode staart. 2: Ik ben familie van de hond. 3: Ik sta bekend als slim en sluw. (vos)',
          '1: Ik tjilp. 2: Ik woon graag in groepjes onder dakpannen. 3: Ik ben een klein bruin vogeltje. (mus)',
          '1: Ik heb vier vleugels. 2: Ik kan stilhangen in de lucht. 3: Ik was eerst een larve in het water. (libel)',
          '1: Ik ben een kever. 2: Het mannetje heeft een soort gewei. 3: Ik ben de grootste kever van België. (vliegend hert)',
          '1: Ik roffel met mijn snavel. 2: Ik hak gaatjes in bomen. 3: Ik ben zwart, wit en een beetje rood. (bonte specht)',
        ],
      },
      pick: 4,
      secret: true,
    },
    scoring: { type: 'aantal', target: 3, unit: 'dieren' },
    sabotage: [
      'Roep snel een dier dat totaal niet past, zodat er een beurt verloren gaat.',
      'Zeg "ik weet het!" en noem dan het verkeerde dier.',
      'Doe alsof een hint eigenlijk over een ander dier gaat.',
    ],
  },
  {
    id: 't-hoepelquiz',
    title: 'De hoepelquiz',
    emoji: '⭕',
    category: 'quiz',
    locations: TUIN_PARK,
    supplies: ['hoepels'],
    minPlayers: 3,
    minutes: 8,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Leg drie hoepels naast elkaar: A, B en C (geen drie hoepels? Leg er cirkels van takjes bij).',
    explain:
      'De spelleider leest een vraag voor met drie antwoorden: A, B of C. Overleg samen en spring dan allemaal tegelijk in dezelfde hoepel. Staat er iemand in een andere hoepel? Dan telt de vraag niet! Doel: {doel} juiste antwoorden.',
    vars: { doel: { makkelijk: [5], normaal: [6], pittig: [6] } },
    list: {
      title: 'Vragen (antwoord enkel voor de spelleider)',
      items: {
        makkelijk: [
          'In welk seizoen vallen de bladeren? A lente, B herfst, C zomer (B)',
          'Wat heeft een boom onder de grond? A wortels, B vleugels, C wielen (A)',
          'Welke kleur heeft gras? A blauw, B groen, C paars (B)',
          'Wat maakt een bij? A kaas, B honing, C chocolade (B)',
          'Waar woont een vogel? A in een nest, B in een doos, C in een emmer (A)',
          'Wat zie je soms als het regent en de zon schijnt? A sneeuw, B een regenboog, C mist (B)',
          'Hoeveel poten heeft een insect? A zes, B vier, C tien (A)',
          'Wat valt er van een dennenboom? A appels, B dennenappels, C bananen (B)',
          'Wanneer is het meestal het warmst? A winter, B zomer, C herfst (B)',
          'Wat eet een konijn graag? A wortels, B vis, C snoep (A)',
          'Wat heb je nodig om te schommelen? A een schommel, B een fiets, C een emmer (A)',
        ],
        normaal: [
          'Wat doet een egel in de winter? A zwemmen, B een winterslaap, C zingen (B)',
          'Van welke boom komt een kastanje? A de kastanjeboom, B de eik, C de den (A)',
          'Welk dier maakt een web? A een mier, B een spin, C een slak (B)',
          'Wat hebben planten nodig om te groeien? A zonlicht, B snoep, C muziek (A)',
          'Hoe heet een babykikker? A een kuiken, B een kikkervisje, C een veulen (B)',
          'Aan welke kant gaat de zon onder? A het oosten, B het westen, C het noorden (B)',
          'Welke boom blijft groen in de winter? A de den, B de eik, C de beuk (A)',
          'Hoeveel vleugels heeft een vlinder? A twee, B vier, C zes (B)',
          'Wat is een paddenstoel? A een plant, B een zwam, C een dier (B)',
          'Welk seizoen komt na de winter? A de herfst, B de lente, C de zomer (B)',
          'Wat maakt een mol? A molshopen, B nesten, C webben (A)',
        ],
        pittig: [
          'Hoe oud kan een eik worden? A 50 jaar, B meer dan 500 jaar, C 10 jaar (B)',
          'Welk dier is geen insect? A een mier, B een spin, C een kever (B)',
          'Waar zitten de oren van een krekel? A op zijn kop, B op zijn voorpoten, C op zijn rug (B)',
          'Wat maken bladeren met zonlicht? A voedsel (suiker), B zout, C lawaai (A)',
          'Welke vogel legt zijn eieren in het nest van andere vogels? A de koekoek, B de merel, C de mus (A)',
          'Hoe heet een rups die zich heeft ingepakt om vlinder te worden? A een pop, B een schelp, C een nest (A)',
          'Hoe heet een grote groep bijen die samen vertrekt? A een zwerm, B een kudde, C een roedel (A)',
          'Wat toont een windwijzer? A de temperatuur, B de windrichting, C de regen (B)',
          'Welke ster staat het dichtst bij de aarde? A de Poolster, B de zon, C de maan (B)',
          'Hoeveel poten heeft een pissebed? A zes, B veertien, C honderd (B)',
          'Welke boom heeft bladeren in de vorm van een waaier? A de ginkgo, B de den, C de hulst (A)',
        ],
      },
      pick: 8,
      secret: true,
    },
    scoring: { type: 'aantal', target: '{doel}', unit: 'antwoorden' },
    sabotage: [
      'Spring met veel zelfvertrouwen als eerste in de verkeerde hoepel.',
      'Blijf twijfelen tussen twee hoepels tot iedereen zenuwachtig wordt.',
      'Zet "per ongeluk" één voet in een andere hoepel, zodat de vraag niet telt.',
    ],
    photo: 'Iedereen samen in één hoepel.',
  },

  // ─────────────── Communicatie ───────────────
  {
    id: 't-blinde-trein',
    title: 'De blinde trein',
    emoji: '🚂',
    category: 'communicatie',
    locations: TUIN_PARK,
    supplies: ['blinddoek', 'pionnen'],
    minPlayers: 4,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Zet {pionnen} pionnen verspreid op het gras, ver weg van trappen, paaltjes en speeltoestellen. De volwassene wandelt mee naast de trein.',
    explain:
      'Maak een trein: iedereen legt de handen op de schouders van wie voor hem staat en doet de ogen dicht (of een blinddoek om), behalve de Machinist achteraan. De Machinist mag niet praten en stuurt met zachte tikjes, die van achter naar voor worden doorgegeven: linkerschouder = links, rechterschouder = rechts, twee schouders = stop. Rij heel traag rond {pionnen} pionnen en terug naar het station!',
    vars: { pionnen: { makkelijk: [2], normaal: [3], pittig: [4] } },
    roles: [{ name: 'Machinist', count: 1, hint: 'Jij staat achteraan en mag als enige kijken. Niet praten, enkel zachte tikjes!' }],
    scoring: { type: 'gelukt' },
    sabotage: [
      'Geef een tikje "per ongeluk" op de verkeerde schouder door.',
      'Geef de tikjes heel traag door.',
      'Als Machinist: tik één keer links als het rechts moet, en verbeter het snel.',
    ],
    dilemma: true,
    photo: 'De blinde trein met de Machinist achteraan.',
  },
  {
    id: 't-lettermannetje',
    title: 'Het lettermannetje',
    emoji: '🧍',
    category: 'communicatie',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De Seiner leest stiekem een geheim woord op de tablet en gaat {afstand} grote stappen verder staan. Zonder geluid vormt de Seiner met armen, benen en lijf de letters van het woord, één voor één. De groep roept elke letter die ze herkennen. Raden jullie het woord? Dan is iemand anders Seiner voor het volgende woord.',
    vars: { afstand: { makkelijk: [10], normaal: [15], pittig: [20] } },
    roles: [{ name: 'Seiner', count: 1, hint: 'Lees het eerste woord stiekem en maak de letters met je lijf. Geen geluid!' }],
    list: {
      title: 'Geheime woorden',
      items: {
        makkelijk: ['ZON', 'BAL', 'BOOM', 'KAT', 'VIS', 'HUT', 'OOI'],
        normaal: ['WINDY', 'KENZO', 'TUIN', 'SCHAT', 'FEEST', 'BLAD', 'MOL'],
        pittig: ['DUVELKE', 'SCHOMMEL', 'PICKNICK', 'KASTANJE', 'EEKHOORN', 'VLINDER', 'GLIJBAAN'],
      },
      pick: 3,
      secret: true,
    },
    scoring: { type: 'aantal', target: 3, unit: 'woorden' },
    sabotage: [
      'Als Seiner: maak één letter spiegelverkeerd.',
      'Roep heel luid een foute letter.',
      'Zeg dat het woord "zeker Engels" is.',
    ],
    photo: 'De Seiner midden in een letter.',
  },
  {
    id: 't-blinde-boerderij',
    title: 'De blinde boerderij',
    emoji: '🐄',
    category: 'communicatie',
    locations: TUIN_PARK,
    supplies: ['blinddoek'],
    minPlayers: 4,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De Boer krijgt een blinddoek. Alle anderen kiezen stiekem een verschillend boerderijdier en gaan verspreid op het gras staan, stil op hun plek. Ze maken enkel hun dierengeluid, geen woorden! De Boer wandelt heel traag op het geluid af, neemt elk dier voorzichtig bij de hand en brengt het naar de stal (de spelleider), {volgorde}.',
    vars: {
      volgorde: {
        makkelijk: ['in eender welke volgorde'],
        normaal: ['van het kleinste naar het grootste dier'],
        pittig: ['in de volgorde van het alfabet'],
      },
    },
    roles: [{ name: 'Boer', count: 1, hint: 'Doe de blinddoek om en luister goed. Wandel heel traag!' }],
    scoring: { type: 'gelukt' },
    sabotage: [
      'Maak een geluid dat op twee dieren tegelijk lijkt.',
      'Zwijg even als de Boer dichtbij komt.',
      'Kies stiekem hetzelfde dier als iemand anders.',
    ],
    photo: 'De Boer met zijn hele kudde in de stal.',
  },
  {
    id: 't-krokodillenbrug',
    title: 'De krokodillenbrug',
    emoji: '🐊',
    category: 'communicatie',
    locations: TUIN_PARK,
    supplies: ['lang-touw'],
    minPlayers: 4,
    minutes: 6,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Leg het lange touw recht op het gras: dat is een smalle brug boven een krokodillenrivier. Iedereen gaat op het touw staan. Ga nu op volgorde staan {volgorde}, zonder te praten en zonder naast het touw te stappen! Help elkaar voorzichtig, niemand duwt. Stapt iemand ernaast? Dan roept de spelleider "Hap!" en staat de groep 10 tellen stil.',
    vars: {
      volgorde: {
        makkelijk: ['van klein naar groot'],
        normaal: ['volgens verjaardag, van januari tot december'],
        pittig: ['volgens de eerste letter van je voornaam, van Z naar A'],
      },
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Toon met je vingers "per ongeluk" een verkeerde verjaardag of letter.',
      'Ga op een plek staan waar je niet hoort en blijf daar tevreden staan.',
      'Stap net met je hiel naast het touw.',
    ],
    dilemma: true,
    photo: 'De hele rij op de brug, in de juiste volgorde.',
  },
  {
    id: 't-robot-tuinman',
    title: 'De robot-tuinman',
    emoji: '🤖',
    category: 'communicatie',
    locations: TUIN_PARK,
    supplies: ['tennisballen', 'emmers'],
    minPlayers: 3,
    minutes: 7,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Leg een tennisbal op de grond en zet een emmer {afstand} grote stappen verder.',
    explain:
      'De Robot doet alleen precies wat hij hoort, en niets meer: "twee stappen vooruit", "draai een kwartje naar links", "buk", "grijp". De groep moet de Robot de tennisbal laten oprapen en in de emmer laten leggen. Jullie mogen samen hoogstens {commandos} commando’s geven!',
    vars: { afstand: { makkelijk: [5], normaal: [8], pittig: [10] }, commandos: { makkelijk: [25], normaal: [20], pittig: [15] } },
    roles: [{ name: 'Robot', count: 1, hint: 'Doe exact wat er gezegd wordt, heel letterlijk. Bliep bliep!' }],
    scoring: { type: 'gelukt' },
    sabotage: [
      'Als Robot: doe een commando net iets té letterlijk.',
      'Roep een commando tegelijk met iemand anders, zodat er één verloren gaat.',
      'Zeg "stap naar links" als je rechts bedoelt.',
    ],
    dilemma: true,
    photo: 'De Robot die de bal in de emmer legt.',
  },

  // ─────────────── Tijdsdruk ───────────────
  {
    id: 't-opruimparade',
    title: 'Windy’s opruimparade',
    emoji: '🧹',
    category: 'tijdsdruk',
    locations: TUIN_PARK,
    supplies: ['tennisballen', 'pionnen', 'hoepels'],
    minPlayers: 3,
    minutes: 5,
    timer: 120,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Verspreid {aantal} spullen (tennisballen, pionnen, ...) over de tuin of een klein stukje park, en leg één hoepel in het midden.',
    explain:
      'Oei, Windy heeft alles laten slingeren en haar bezoek komt zo! Breng alle {aantal} spullen in de hoepel voor de tijd om is. Maar: je mag maar één ding tegelijk dragen, en je moet terug naar de hoepel hinken! Blijf binnen het speelveld dat de volwassene aanduidt.',
    vars: { aantal: { makkelijk: [10], normaal: [15], pittig: [20] } },
    scoring: { type: 'aantal', target: '{aantal}', unit: 'spullen' },
    sabotage: [
      'Hink extra traag en neem een omweg.',
      'Leg een ding net buiten de hoepel.',
      'Draag stiekem niets en doe alsof je nog zoekt.',
    ],
  },
  {
    id: 't-schaduwstappen',
    title: 'Schaduwstappen',
    emoji: '🌤️',
    category: 'tijdsdruk',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 5,
    timer: 120,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Zon, kom maar op! Stap samen op de schaduw van {aantal} verschillende dingen: een boom, een bank, een paal, een fiets... Roep telkens luid: "Schaduw van de...!" Elk ding telt één keer. Geen zon? Dan tikken jullie de dingen zelf aan. Blijf in de buurt van de volwassene.',
    vars: { aantal: { makkelijk: [6], normaal: [10], pittig: [14] } },
    scoring: { type: 'aantal', target: '{aantal}', unit: 'schaduwen' },
    sabotage: [
      'Stap op een schaduw die al geteld is en roep er een andere naam bij.',
      'Zeg dat een schaduw "niet echt" meetelt.',
      'Loop naar iets dat helemaal geen schaduw heeft.',
    ],
    photo: 'Iedereen die op dezelfde grote schaduw staat.',
  },
  {
    id: 't-tik-tak-tik',
    title: 'Tik-tak-tik!',
    emoji: '👆',
    category: 'tijdsdruk',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 5,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De spelleider roept een opdracht, zoals "Iets van hout!" Binnen {seconden} seconden moet iedereen iets aanraken dat klopt, en niemand mag hetzelfde ding aanraken als een ander! Lukt het {doel} keer na elkaar?',
    vars: { seconden: { makkelijk: [10], normaal: [7], pittig: [5] }, doel: { makkelijk: [5], normaal: [6], pittig: [8] } },
    list: {
      title: 'Raak aan...',
      items: {
        normaal: ['iets van hout', 'iets groens', 'iets ronds', 'iets van metaal', 'iets zachts', 'iets dat ouder is dan jij', 'iets dat kan draaien', 'iets kouds', 'iets met een hoek', 'iets dat je kan openen', 'iets dat in de zon staat', 'iets met een letter erop', 'iets dat groeit', 'iets geels'],
      },
      pick: 10,
      secret: false,
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Raak net hetzelfde ding aan als iemand anders.',
      'Twijfel heel lang, tot de tijd bijna om is.',
      'Raak iets aan dat er alleen een beetje op lijkt.',
    ],
  },
  {
    id: 't-red-de-picknick',
    title: 'Red de picknick!',
    emoji: '🧺',
    category: 'tijdsdruk',
    locations: TUIN_PARK,
    supplies: ['handdoeken', 'knuffels', 'plastiekbekers'],
    minPlayers: 4,
    minutes: 5,
    timer: 90,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Leg een handdoek als picknickkleed neer met {aantal} lege bekertjes en een paar knuffels erop. Duid een schuilplaats aan (een boom, het tuinhuis) op {afstand} grote stappen.',
    explain:
      'Windy ziet een donkere wolk aankomen! Breng de hele picknick (de handdoek, de {aantal} bekertjes en de knuffels) naar de schuilplaats, {afstand} grote stappen verder. Maar elk ding moet door twee kinderen tegelijk gedragen worden, en de bekertjes moeten rechtop blijven. Snel, voor het "onweer" losbarst!',
    vars: { aantal: { makkelijk: [4], normaal: [6], pittig: [8] }, afstand: { makkelijk: [10], normaal: [15], pittig: [20] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Laat een bekertje "per ongeluk" omvallen bij het oppakken.',
      'Neem een ding alleen mee, zodat het niet telt.',
      'Loop eerst naar de verkeerde schuilplaats.',
    ],
    photo: 'De geredde picknick in de schuilplaats.',
  },
  {
    id: 't-fluitformaties',
    title: 'De fluitformaties',
    emoji: '📯',
    category: 'tijdsdruk',
    locations: TUIN_PARK,
    supplies: ['fluitje'],
    minPlayers: 3,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Luister goed naar het fluitje! 1 keer: allemaal in een rij, van klein naar groot. 2 keer: een kring, hand in hand. 3 keer: iedereen raakt dezelfde boom of paal aan. 4 keer: {vier}. Jullie hebben telkens {seconden} seconden. Lukt het {doel} keer na elkaar?',
    vars: {
      vier: { makkelijk: ['allemaal op de grond zitten'], normaal: ['een grote ster, liggend op het gras met de voeten naar het midden'], pittig: ['samen de letter T vormen, liggend op het gras'] },
      seconden: { makkelijk: [10], normaal: [8], pittig: [6] },
      doel: { makkelijk: [5], normaal: [6], pittig: [8] },
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Tel het aantal fluitsignalen luidop verkeerd mee.',
      'Ga op de verkeerde plek in de rij staan.',
      'Neem net te laat de hand van je buur vast.',
    ],
    photo: 'De liggende ster van bovenaf.',
  },

  // ─────────────── Speuren ───────────────
  {
    id: 't-krijtpijlen',
    title: 'Het krijtpijlenspoor',
    emoji: '➡️',
    category: 'speuren',
    locations: TUIN_PARK,
    supplies: ['stoepkrijt'],
    minPlayers: 3,
    minutes: 12,
    timer: 480,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Teken met stoepkrijt een spoor van {pijlen} pijlen langs paden of het terras. Schrijf bij sommige pijlen een letter, zodat ze samen het woord {woord} vormen. Teken ook 3 valse pijlen met een kruisje erin.',
    explain:
      'Volg het krijtspoor! Pas op: pijlen met een kruisje erin zijn nep en sturen jullie de verkeerde kant op. Bij sommige pijlen staat een letter. Onthoud ze allemaal en vorm er op het einde een woord mee. Blijf altijd in de buurt van de volwassene.',
    vars: {
      pijlen: { makkelijk: [6], normaal: [10], pittig: [14] },
      woord: { makkelijk: ['BAL', 'ZON'], normaal: ['SCHAT', 'WINDY'], pittig: ['DUVELKE', 'GEHEIMPJE'] },
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Wijs enthousiast een valse pijl aan.',
      'Onthoud een letter "per ongeluk" fout en zeg die heel zeker.',
      'Loop een beetje voorop en sla een pijl over.',
    ],
    dilemma: true,
    photo: 'De speurders bij de laatste pijl.',
  },
  {
    id: 't-diersporen',
    title: 'Sporen van dieren',
    emoji: '🐾',
    category: 'speuren',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    timer: 360,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Dieren laten overal sporen achter! Speur samen naar de sporen van de lijst. Wijs ze aan en roep "Spoor!", maar raak niets aan: we kijken enkel. Blijf in de buurt van de volwassene. Hoeveel sporen vinden jullie?',
    list: {
      title: 'Speur naar...',
      items: {
        makkelijk: ['een blad met gaatjes (daar heeft iemand van gesmuld)', 'een spinnenweb', 'een veer', 'een leeg slakkenhuisje', 'een mierenstraat', 'een vogel die iets eet', 'een vlinder of bij op een bloem', 'een gat in de grond', 'een molshoop'],
        normaal: ['een blad met gaatjes', 'een spinnenweb', 'een veer', 'een mierenstraat', 'een molshoop', 'een gat in de grond', 'een afgeknaagde dennenappel of noot', 'een glinsterend slakkenspoor', 'een nest in een boom', 'pootafdrukken in zand of aarde'],
        pittig: ['een boom met een spechtengat', 'een cocon of een pop', 'een opgerold blad (daar woont een insect in)', 'een blad dat enkel aan de rand is opgegeten', 'krassen in de schors', 'een mierenhoop', 'een vlinder met open vleugels', 'een kever', 'een afgeknaagde dennenappel', 'drie verschillende veren'],
      },
      pick: 6,
      secret: false,
    },
    scoring: { type: 'aantal', target: 6, unit: 'sporen' },
    sabotage: [
      'Roep "Spoor!" bij iets dat helemaal geen spoor is.',
      'Stuur de groep naar het midden van het gras, waar weinig te zien is.',
      'Zeg dat een spoor "te klein om mee te tellen" is.',
    ],
    photo: 'De speurneuzen bij hun mooiste spoor.',
  },
  {
    id: 't-kompasschat',
    title: 'De kompasschat',
    emoji: '🧭',
    category: 'speuren',
    locations: TUIN_PARK,
    supplies: ['kompas', 'knuffels', 'papier', 'stiften'],
    minPlayers: 3,
    minutes: 10,
    timer: 420,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Verstop een knuffel (de schat). Schrijf vanaf een startpunt een route van {stappen} kompasopdrachten op papier, bijvoorbeeld "5 grote stappen naar het noorden, 3 naar het oosten". Tel zelf met kinderstappen.',
    explain:
      'Met het kompas volgen jullie de geheime route van de spelleider. Hou het kompas plat en draai tot de naald naar de N wijst. Tel de stappen samen en luidop! Vinden jullie de verstopte schat? Blijf in de buurt van de volwassene.',
    vars: { stappen: { makkelijk: [3], normaal: [5], pittig: [7] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Zet net iets kleinere of grotere stappen dan de anderen.',
      'Hou het kompas scheef als jij het mag vasthouden.',
      'Zeg dat het oosten links is (als je naar het noorden kijkt, is het rechts).',
    ],
    dilemma: true,
    photo: 'De vinders met de schat en het kompas.',
  },
  {
    id: 't-verrekijker',
    title: 'De verrekijkerverkenners',
    emoji: '🔭',
    category: 'speuren',
    locations: TUIN_PARK,
    supplies: ['verrekijker'],
    minPlayers: 3,
    minutes: 8,
    timer: 360,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Met de verrekijker speuren jullie in de verte! Zoek alles van de lijst. Wie iets ziet, geeft de verrekijker door, zodat een tweede speurder het kan bevestigen. Pas dan telt het. Nooit met de verrekijker in de zon kijken!',
    list: {
      title: 'Speur in de verte naar...',
      items: {
        normaal: ['een vogel op een tak', 'een vliegtuig', 'een wolk die op een dier lijkt', 'een rood dak', 'een vlag', 'een kerktoren of hoog gebouw', 'een hond die gaat wandelen', 'iets geels in een boom', 'een schoorsteen', 'een nest', 'een fiets', 'een vogel in de lucht'],
        pittig: ['een vogel met iets roods', 'een vliegtuig met een witte streep erachter', 'een huisnummer van ver', 'een eekhoorn', 'drie wolken die op elkaar lijken', 'een weerhaan of windwijzer', 'een zwerm vogels', 'iemand met een hoed of pet', 'een klok', 'een antenne op een dak'],
      },
      pick: 6,
      secret: false,
    },
    scoring: { type: 'aantal', target: 6, unit: 'dingen' },
    sabotage: [
      'Zeg dat je iets ziet en geef de verrekijker dan scheef door.',
      'Draai "per ongeluk" aan het wieltje, zodat alles wazig wordt.',
      'Hou de verrekijker lang vast en beschrijf alles heel traag.',
    ],
    photo: 'Iemand die door de verrekijker tuurt, met de anderen die wijzen.',
  },

  // ─────────────── Foto ───────────────
  {
    id: 't-reuzen-en-kabouters',
    title: 'Reuzen en kabouters',
    emoji: '📷',
    category: 'foto',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    timer: 360,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Met een foto kan je toveren! Wie ver weg staat, lijkt een kabouter, en wie dichtbij staat, een reus. Maak samen de toverfoto’s van de lijst; de spelleider fotografeert. Pas als iedereen vindt dat de truc lukt, telt de foto.',
    list: {
      title: 'Toverfoto’s',
      items: {
        normaal: [
          'Iemand houdt een ander in de palm van zijn hand.',
          'Een reus gebruikt een boom als wandelstok.',
          'Iemand lijkt op het hoofd van een ander te staan.',
          'Een kabouter kruipt uit een schoen.',
          'Iemand houdt de zon in zijn hand.',
          'Iemand tilt een huis op met twee vingers.',
          'Twee reuzen pakken de spelleider op.',
          'Iemand wordt weggeblazen als een pluisje.',
        ],
      },
      pick: 4,
      secret: false,
    },
    scoring: { type: 'aantal', target: 4, unit: 'foto’s' },
    sabotage: [
      'Ga net iets te ver opzij staan, zodat de truc niet klopt.',
      'Beweeg op het moment van de foto.',
      'Kijk net in de verkeerde richting.',
    ],
    photo: 'De grappigste toverfoto.',
  },
  {
    id: 't-schaduwmonster',
    title: 'Het schaduwmonster',
    emoji: '👾',
    category: 'foto',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Zoek een plek in de zon. Maak samen met jullie schaduwen één grote figuur op de grond: {figuur}. De spelleider maakt een foto van de schaduw. Lijkt het echt? Dan is het gelukt! Geen zon? Maak de figuur dan liggend op het gras.',
    vars: {
      figuur: {
        makkelijk: ['een monster met veel armen', 'een grote bloem'],
        normaal: ['een spin met acht poten', 'een draak met vleugels', 'een vlinder'],
        pittig: ['een kasteel met twee torens', 'een octopus die zwaait', 'het woord HOI'],
      },
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Ga net iets te ver weg staan, zodat jouw schaduw loskomt van de rest.',
      'Beweeg je armen op het moment van de foto.',
      'Stel voor om met je gezicht naar de zon te staan (dan valt je schaduw achter je en zie je niets).',
    ],
    photo: 'De schaduwfiguur met de makers erbij.',
  },
  {
    id: 't-filmaffiche',
    title: 'Het speeltuinfilmaffiche',
    emoji: '🎬',
    category: 'foto',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 9,
    timer: 420,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De speeltuin is een filmstudio! Maak een spannend filmaffiche bij de titels van de lijst: iedereen speelt een rol, met de schommel, glijbaan, bank of een boom als decor. Niet op hoge dingen klimmen! Na 10 tellen stilstaan maakt de spelleider de foto.',
    list: {
      title: 'Filmtitels',
      items: {
        normaal: ['De ontsnapping van ’t Duvelke', 'Windy en de verdwenen pruik', 'Kenzo redt de wereld', 'De laatste dennenappel', 'Aanval van de reuzenmieren', 'Het geheim van de zandbak', 'Superhelden op de schommel', 'De grote picknickramp'],
      },
      pick: 3,
      secret: false,
    },
    scoring: { type: 'aantal', target: 3, unit: 'affiches' },
    sabotage: [
      'Kijk vrolijk in de camera terwijl je bang moet kijken.',
      'Knipper met je ogen net als de foto genomen wordt.',
      'Stel een pose voor die niemand begrijpt.',
    ],
    photo: 'Het beste filmaffiche, met de titel luid voorgelezen.',
  },
  {
    id: 't-gezichten-natuur',
    title: 'Gezichten in de natuur',
    emoji: '😮',
    category: 'foto',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    timer: 420,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Soms lijkt een knoest in een boom op een neus, of een steen op een lachend gezicht. Zoek samen {aantal} dingen die op een gezicht lijken en laat de spelleider er een foto van maken. Jullie mogen er niets aan veranderen: het gezicht moet er al zijn! Blijf in de buurt van de volwassene.',
    vars: { aantal: { makkelijk: [3], normaal: [5], pittig: [7] } },
    scoring: { type: 'aantal', target: '{aantal}', unit: 'gezichten' },
    sabotage: [
      'Hou vol dat iets op een gezicht lijkt, terwijl het nergens op lijkt.',
      'Loop weg van de plek waar de groep net iets goeds vond.',
      'Zeg bij elk gevonden gezicht: "Dat is maar een half gezicht."',
    ],
    photo: 'Het grappigste natuurgezicht, met iedereen die het nadoet.',
  },

  // ─────────────── Beweging ───────────────
  {
    id: 't-windy-zegt',
    title: 'Windy zegt...',
    emoji: '📢',
    category: 'beweging',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 5,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Doe enkel wat de spelleider zegt als de zin begint met "Windy zegt". Begint de zin met "’t Duvelke zegt", dan doe je NIETS! Iedereen doet tegelijk mee: vergist iemand zich, dan begint het tellen opnieuw. Halen jullie {doel} opdrachten na elkaar zonder fout?',
    vars: { doel: { makkelijk: [8], normaal: [12], pittig: [16] } },
    list: {
      title: 'Opdrachten om te roepen (wissel Windy en ’t Duvelke af!)',
      items: {
        normaal: ['spring drie keer', 'tik een boom aan', 'draai een rondje', 'sta op één been', 'raak je tenen aan', 'doe een kikkersprong', 'zwaai naar de buren', 'ga op je hurken zitten', 'klap vijf keer', 'doe een flamingo', 'stap drie keer achteruit', 'roep "hoera!"', 'draai je armen als een windmolen', 'maak jezelf zo groot mogelijk', 'maak jezelf zo klein mogelijk', 'hink naar de dichtste boom', 'doe alsof je een ijsje eet', 'geef jezelf een knuffel', 'loop op de plaats'],
      },
      pick: 16,
      secret: false,
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Beweeg een klein beetje bij een "’t Duvelke zegt"-opdracht, zodat je buur ook begint.',
      'Wacht net iets te lang bij een echte "Windy zegt".',
      'Fluister "dat was Windy, hoor" als het ’t Duvelke was.',
    ],
  },
  {
    id: 't-dierenestafette',
    title: 'De dierenestafette',
    emoji: '🦩',
    category: 'beweging',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Estafette met een dierlijke twist! Markeer met twee takjes een start en een keerpunt op {afstand} grote stappen. De spelleider roept voor elke loper een dier van de lijst, en die loper gaat zo heen en terug: als krab, kikker, flamingo... Tik de volgende aan. Komt iedereen {rondes} aan de beurt voor de tijd om is?',
    vars: { afstand: { makkelijk: [6], normaal: [8], pittig: [10] }, rondes: { makkelijk: ['één keer'], normaal: ['één keer'], pittig: ['twee keer'] } },
    list: {
      title: 'Dierenloopjes',
      items: {
        normaal: ['krab (zijwaarts op handen en voeten)', 'kikker (grote sprongen vanuit hurkzit)', 'flamingo (hinkend op één been)', 'pinguïn (kleine pasjes, armen tegen je lijf)', 'olifant (traag, met je arm als slurf)', 'kangoeroe (sprongen met twee voeten tegelijk)', 'eend (waggelend op je hurken)', 'paard (galopperen)', 'beer (op handen en voeten)', 'struisvogel (met hoge knieën)', 'rups (kleine stapjes, handen op je knieën)', 'robot (stijve benen en armen)'],
      },
      pick: 8,
      secret: false,
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Doe je dier extra traag, "omdat het zo hoort".',
      'Vergeet de volgende aan te tikken en loop gewoon door.',
      'Keer net vóór het keerpunt al om, zodat je opnieuw moet.',
    ],
    photo: 'Het gekste dierenloopje in actie.',
  },
  {
    id: 't-springslang',
    title: 'De springslang',
    emoji: '🐍',
    category: 'beweging',
    locations: TUIN_PARK,
    supplies: ['springtouw'],
    minPlayers: 4,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Twee Slangenbezweerders houden elk een uiteinde van het springtouw vast en laten het over het gras kronkelen als een slang, altijd op de grond. De rest springt er om de beurt over, zonder de slang te raken. Na elke ronde kronkelt de slang een beetje sneller en wisselen de Slangenbezweerders. Springt iedereen {rondes} rondes zonder aanraking?',
    vars: { rondes: { makkelijk: [3], normaal: [4], pittig: [5] } },
    roles: [{ name: 'Slangenbezweerder', count: 2, hint: 'Laat het touw over de grond kronkelen, nooit omhoog zwaaien.' }],
    scoring: { type: 'aantal', target: '{rondes}', unit: 'rondes' },
    sabotage: [
      'Als Slangenbezweerder: kronkel net iets onvoorspelbaarder als iemand springt.',
      'Spring net een tikje te laat.',
      'Tel luidop af, maar net te vroeg.',
    ],
    photo: 'Iemand hoog boven de springslang.',
  },
  {
    id: 't-tweelingparcours',
    title: 'Het tweelingparcours',
    emoji: '👯',
    category: 'beweging',
    locations: TUIN_PARK,
    supplies: ['hoepels', 'pionnen', 'springtouw'],
    minPlayers: 4,
    minutes: 10,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Bouw samen een parcours: hoepels om in te springen, pionnen om rond te slalommen en een springtouw op de grond om over te balanceren. Dan komt de twist: je doet het parcours per twee, hand in hand, en jullie mogen elkaar nooit loslaten! Oneven aantal? Dan loopt er een drieling. Halen alle tweelingen de finish {extra} voor de tijd om is?',
    vars: { extra: { makkelijk: ['één keer'], normaal: ['één keer, zonder een pion om te stoten,'], pittig: ['één keer, zonder een pion om te stoten en achterwaarts over het touw,'] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Spring net iets vroeger dan je tweelingbroer of -zus.',
      'Laat heel even los in een bocht en doe alsof er niets gebeurde.',
      'Zet een pion net iets moeilijker als je meehelpt bouwen.',
    ],
    dilemma: true,
    photo: 'Een tweeling hand in hand in de hoepels.',
  },
  {
    id: 't-bewegingsdobbel',
    title: 'De bewegingsdobbelsteen',
    emoji: '🎲',
    category: 'beweging',
    locations: TUIN_PARK,
    supplies: ['dobbelstenen'],
    minPlayers: 3,
    minutes: 7,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Gooi twee dobbelstenen. De eerste zegt WAT jullie doen (1 = de eerste beweging van de lijst, 2 = de tweede...), de tweede zegt HOEVEEL keer. Iedereen doet het tegelijk en jullie tellen samen luidop. Iemand mistelt? Dan doen jullie die worp opnieuw. Halen jullie {worpen} worpen voor de tijd om is?',
    vars: { worpen: { makkelijk: [5], normaal: [7], pittig: [10] } },
    list: {
      title: 'Bewegingen (1 tot 6)',
      items: {
        normaal: ['kikkersprongen', 'rondjes draaien', 'keer je tenen aanraken', 'sterrensprongen', 'tellen op één been staan', 'keer "Windy!" roepen terwijl je springt', 'hurksprongen', 'keer klappen boven je hoofd', 'stappen achteruit', 'keer hinken'],
      },
      pick: 6,
      secret: false,
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Tel luidop net een getal te snel.',
      'Doe een beweging die net niet klopt, zodat anderen gaan twijfelen.',
      'Gooi de dobbelsteen "per ongeluk" ver weg, zodat jullie tijd verliezen.',
    ],
    photo: 'Iedereen tegelijk in een sterrensprong.',
  },
  {
    id: 't-hoepeleilanden',
    title: 'De hoepeleilanden',
    emoji: '🏝️',
    category: 'beweging',
    locations: TUIN_PARK,
    supplies: ['hoepels'],
    minPlayers: 4,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Leg de hoepels verspreid op het gras: dat zijn eilanden in de zee. Iedereen wandelt, huppelt of danst rond. Roept de spelleider "Haaien!", dan moet iedereen binnen 5 tellen met minstens één voet in een hoepel staan. Na elke ronde verdwijnt er een eiland, maar niemand mag in het water blijven! Help elkaar, niemand duwt. Lukt het met nog {eilanden} over?',
    vars: { eilanden: { makkelijk: ['3 eilanden'], normaal: ['2 eilanden'], pittig: ['1 eiland'] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Ga midden in een hoepel staan, zodat er minder plaats is voor de rest.',
      'Kom net na de vijf tellen aan.',
      'Stel voor dat iedereen naar hetzelfde eiland loopt, ook als er nog andere zijn.',
    ],
    photo: 'Iedereen samengepropt op het laatste eiland.',
  },
  {
    id: 't-sluipschat',
    title: 'De sluipschat',
    emoji: '🤫',
    category: 'beweging',
    locations: TUIN_PARK,
    supplies: [],
    minPlayers: 3,
    minutes: 6,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De spelleider staat met de rug naar de groep, op {afstand} grote stappen, met een "schat" naast zich (een schoen, een pet of een knuffel). De groep moet de schat stilletjes stelen en terugbrengen naar de start. Hoort de spelleider iemand, dan wijst die naar hem of haar: terug naar de start! De spelleider mag niet kijken, enkel luisteren. Niet rennen!',
    vars: { afstand: { makkelijk: [10], normaal: [15], pittig: [20] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Stap "per ongeluk" op een krakend takje of droog blad.',
      'Fluister net iets te luid een tip.',
      'Begin te giechelen als iemand bijna bij de schat is.',
    ],
    dilemma: true,
  },
  {
    id: 't-sprongcode',
    title: 'De sprongcode',
    emoji: '🔐',
    category: 'beweging',
    locations: TUIN_PARK,
    supplies: ['stoepkrijt'],
    minPlayers: 3,
    minutes: 7,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Teken met stoepkrijt op het terras of een pad een groot veld met 9 vakjes en zet de cijfers 1 tot 9 door elkaar in de vakjes.',
    explain:
      'De spelleider roept een geheime code van {cijfers} cijfers. Wie aan de beurt is, springt met twee voeten tegelijk van vakje naar vakje, in de juiste volgorde, en roept op het einde: "Code gekraakt!" Daarna is de volgende aan de beurt met een nieuwe code. Doel: {doel} juiste codes.',
    vars: { cijfers: { makkelijk: [3], normaal: [4], pittig: [5] }, doel: { makkelijk: [4], normaal: [6], pittig: [8] } },
    scoring: { type: 'aantal', target: '{doel}', unit: 'codes' },
    sabotage: [
      'Roep "helpend" een fout cijfer als iemand twijfelt.',
      'Wijs een vakje aan dat net naast het juiste ligt.',
      'Doe alsof je de code vergeten bent als jij moet helpen onthouden.',
    ],
    photo: 'Een springer midden in de code.',
  },
];
