import type { LocationId } from '../types';
import type { TaskDef } from './types';

const OVERAL: LocationId[] = ['binnen', 'tuin', 'straat', 'bos', 'park', 'dorp', 'strand'];
const RUSTIG_BUITEN: LocationId[] = ['tuin', 'bos', 'park', 'strand'];
const BINNEN_TUIN: LocationId[] = ['binnen', 'tuin'];
const ALLE_NIVEAUS = ['makkelijk', 'normaal', 'pittig'] as const;

/**
 * De ingebouwde opdrachten. Sabotagetips zijn altijd stiekem en veilig:
 * nooit duwen, trekken, iets kapotmaken of iemand pijn doen.
 */
export const BUILTIN_TASKS: TaskDef[] = [
  // ─────────────── Zoeken ───────────────
  {
    id: 'wasknijper-jacht',
    title: 'De wasknijperjacht',
    emoji: '🪝',
    category: 'zoeken',
    locations: BINNEN_TUIN,
    supplies: ['wasknijpers'],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Verstop {aantal} wasknijpers (binnen of in de tuin) terwijl de groep niet kijkt.',
    explain:
      'Er zijn {aantal} wasknijpers verstopt! Zoek ze allemaal voor de tijd om is. Elke gevonden wasknijper breng je meteen naar de spelleider.',
    vars: { aantal: { makkelijk: [8], normaal: [12], pittig: [15] } },
    scoring: { type: 'aantal', target: '{aantal}', unit: 'wasknijpers' },
    sabotage: [
      'Vind je een wasknijper als niemand kijkt? Laat hem liggen en loop gewoon verder.',
      'Zeg dat je een plek al goed doorzocht hebt, ook als je er maar snel gekeken hebt.',
      'Roep één keer dat je in een hoek iets zag, waar dan niets blijkt te liggen.',
      'Vergeet een gevonden wasknijper "per ongeluk" in je zak tot de tijd bijna om is.',
    ],
    detective: [
      'Let op wie lang op één plek staat zonder echt te zoeken.',
      'Zegt iemand dat een plek al doorzocht is? Kijk daar zelf nog eens.',
      'Wie stuurt de groep naar een hoek waar dan niets blijkt te liggen?',
      'Kijk wie bijna nooit een wasknijper naar de spelleider brengt.',
    ],
    dilemma: true,
    photo: 'Iedereen met een wasknijper aan zijn oor.',
  },
  {
    id: 'kleurenjacht',
    title: 'Kleurenjacht',
    emoji: '🌈',
    category: 'zoeken',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Zoek zo snel mogelijk voorwerpen in deze kleuren en leg ze samen op één plek (buiten: wijs ze aan of maak een foto). Elke kleur telt één keer.',
    list: {
      title: 'Zoek iets dat...',
      items: {
        makkelijk: ['rood is', 'geel is', 'blauw is', 'groen is', 'wit is', 'zwart is', 'roze is', 'oranje is'],
        normaal: ['rood is', 'geel is', 'blauw is', 'groen is', 'paars is', 'oranje is', 'goud of zilver is', 'gestreept is', 'gestipt is', 'doorzichtig is'],
        pittig: ['lichtblauw is', 'donkergroen is', 'bruin én rond is', 'gestreept is', 'gestipt is', 'doorzichtig is', 'drie kleuren heeft', 'glanzend is', 'turquoise is', 'beige is'],
      },
      pick: 8,
      secret: false,
    },
    scoring: { type: 'aantal', target: 8, unit: 'kleuren' },
    sabotage: [
      'Breng één keer iets dat bijna de goede kleur heeft en zeg dat het volgens jou klopt.',
      'Zoek net iets trager dan de rest, alsof je heel goed aan het kijken bent.',
      'Breng iets voor een kleur die al gevonden is, alsof je dat niet wist.',
      'Zeg bij een moeilijke kleur dat die hier vast nergens te vinden is.',
    ],
    detective: [
      'Let op wie dingen brengt die net niet de juiste kleur hebben.',
      'Wie brengt iets voor een kleur die jullie al hebben?',
      'Wie zegt snel dat een kleur hier toch niet te vinden is?',
    ],
    photo: 'Alle gevonden kleuren netjes op een rij.',
  },
  {
    id: 'natuurbingo',
    title: 'Natuurbingo',
    emoji: '🍂',
    category: 'zoeken',
    locations: ['bos', 'park', 'tuin'],
    supplies: [],
    minPlayers: 3,
    minutes: 10,
    timer: 420,
    difficulties: [...ALLE_NIVEAUS],
    explain: 'Verzamel alles van de bingokaart en breng het naar de spelleider. Enkel dingen die al op de grond liggen: niets afbreken!',
    list: {
      title: 'Bingokaart',
      items: {
        makkelijk: ['een dennenappel', 'een blad', 'een steentje', 'een takje', 'iets geels', 'een eikel of kastanje', 'iets zachts', 'iets ronds', 'iets bruins', 'een veer'],
        normaal: ['een dennenappel', 'een blad groter dan je hand', 'een helemaal rond steentje', 'een Y-vormig takje', 'een veer', 'iets dat lekker ruikt', 'drie verschillende bladeren', 'een eikel of kastanje', 'iets dat rood is', 'mos'],
        pittig: ['een blad met gekartelde rand', 'een steentje met een streep', 'een takje exact zo lang als je arm', 'een veer', 'vijf verschillende bladeren', 'iets dat een dier gegeten heeft', 'een platte steen', 'een dennenappel die nog dicht is', 'iets dat van een mens komt (afval)', 'mos'],
      },
      pick: 9,
      secret: false,
    },
    scoring: { type: 'aantal', target: 9, unit: 'vakjes' },
    sabotage: [
      'Breng één keer iets dat net niet klopt, zoals een blad dat te klein is.',
      'Roep één keer dat je verderop iets zag, waar dan niets blijkt te liggen.',
      'Zoek naar een vakje dat al gevonden is, alsof je het vergeten was.',
      'Twijfel luidop of een goed ding wel echt telt.',
    ],
    detective: [
      'Let op wie dingen brengt die net niet bij het vakje passen.',
      'Wie stuurt de groep naar een plek waar dan niets ligt?',
      'Wie zoekt naar dingen die jullie al gevonden hebben?',
    ],
    photo: 'De volle bingokaart met alle spullen.',
  },
  {
    id: 'speurlijst-buurt',
    title: 'Speurlijst in de buurt',
    emoji: '🏘️',
    category: 'zoeken',
    locations: ['straat', 'dorp'],
    supplies: [],
    minPlayers: 3,
    minutes: 12,
    timer: 600,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Wandel samen met de volwassene door de buurt en zoek alles van de lijst. Wijs het aan en roep het luid. Blijf altijd samen en op de stoep!',
    list: {
      title: 'Zoek in de buurt...',
      items: {
        normaal: ['een brievenbus', 'een huisnummer met een 7', 'een fiets met een mandje', 'een kat', 'een rode deur', 'een verkeersbord met een fiets', 'een tuinkabouter', 'iemand die een hond uitlaat', 'een huisnummer boven de 50', 'een bloembak', 'een raam met gordijnen met bloemen', 'een auto met een trekhaak'],
        pittig: ['een huisnummer met drie dezelfde cijfers', 'een straatnaam met een dierennaam', 'een blauwe auto met een fietsdrager', 'een deur met een klopper', 'een schoorsteen die rookt', 'een verkeersbord met een uitroepteken', 'een bel met drie namen', 'een tuinkabouter', 'een kat op een vensterbank', 'een winkel'],
      },
      pick: 8,
      secret: false,
    },
    scoring: { type: 'aantal', target: 8, unit: 'dingen' },
    sabotage: [
      'Zeg één keer dat je iets van de lijst ziet, en zeg dan dat het "toch niet" klopt.',
      'Treuzel een beetje, maar blijf wel altijd bij de groep.',
      'Twijfel luidop of iets wel echt telt.',
      'Zie je iets van de lijst? Zeg niets en wacht tot iemand anders het ziet.',
    ],
    detective: [
      'Let op wie iets "ziet" dat er dan niet blijkt te zijn.',
      'Wie twijfelt vaak of iets wel telt?',
      'Wie loopt achteraan en vindt bijna nooit iets?',
    ],
    photo: 'De hele groep bij het leukste ding van de lijst.',
  },
  {
    id: 'schelpenjacht',
    title: 'Schelpenjacht',
    emoji: '🐚',
    category: 'zoeken',
    locations: ['strand'],
    supplies: ['emmers'],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain: 'Verzamel samen {aantal} verschillende schelpen in de emmer. Elke soort telt maar één keer!',
    vars: { aantal: { makkelijk: [6], normaal: [10], pittig: [14] } },
    scoring: { type: 'aantal', target: '{aantal}', unit: 'soorten' },
    sabotage: [
      'Leg één keer een schelp in de emmer die er al in zit, en zeg dat ze toch anders is.',
      'Zoek een eind weg van de emmer, zodat je lang moet lopen met elke schelp.',
      'Zeg bij een nieuwe soort dat die al in de emmer zit.',
    ],
    detective: [
      'Let op wie schelpen brengt die al in de emmer zitten.',
      'Zegt iemand dat een schelp er al in zit? Kijk zelf even na.',
      'Wie loopt ver weg van de emmer en brengt weinig terug?',
    ],
    photo: 'Alle schelpen op een rij in het zand.',
  },

  // ─────────────── Raadsels ───────────────
  {
    id: 'codeslot',
    title: 'Het codeslot',
    emoji: '🔐',
    category: 'raadsels',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De schatkist zit op slot! Elk raadsel geeft één cijfer van de code. Los ze samen op en zeg de volledige code tegen de spelleider. Die kijkt of ze klopt.',
    list: {
      title: 'Raadsels (antwoorden enkel voor de spelleider)',
      items: {
        makkelijk: [
          'Hoeveel poten heeft een spin? (8)',
          'Hoeveel wielen heeft een driewieler? (3)',
          'Hoeveel dagen heeft een week? (7)',
          'Hoeveel ogen heeft een mens? (2)',
          'Hoeveel kleuren heeft de Belgische vlag? (3)',
          'Hoeveel poten heeft een kip? (2)',
        ],
        normaal: [
          'Ik ben een getal. Tel je mij bij mezelf op, dan krijg je 12. (6)',
          'Hoeveel poten hebben een paard en een kip samen? (6)',
          'Hoeveel poten hebben 2 eenden samen? (4)',
          'Het aantal letters in het woord WINDY. (5)',
          'Een hand heeft 5 vingers. Hoeveel vingers hebben 2 handen min 1? (9)',
          'Hoeveel hoeken heeft een driehoek plus een vierkant samen, gedeeld door 7? (1)',
        ],
        pittig: [
          'Welk cijfer komt na 1, 1, 2, 3, 5? (8)',
          'Ik ben oneven. Haal je een letter weg, dan word ik even. Welk getal? (7, zeven → even)',
          'Hoeveel keer kan je 5 aftrekken van 25? (1 keer: daarna is het 20)',
          'Een klok slaat 6 uur in 5 seconden. Hoe veel slagen zijn er? (6)',
          'Het aantal letters in DUVELKE min het aantal letters in KENZO. (2)',
          'Wat is de helft van 2 plus 2? (3)',
        ],
      },
      pick: 3,
      secret: true,
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Roep bij één raadsel snel een fout cijfer, alsof je het zeker weet.',
      'Zeg de cijfers van de code één keer in de verkeerde volgorde op.',
      'Twijfel luidop bij een juist antwoord: "Is het niet eerder...?"',
    ],
    detective: [
      'Let op wie snel een cijfer roept dat fout blijkt.',
      'Wie haalt de volgorde van de cijfers door elkaar?',
      'Wie maakt de groep onzeker bij een antwoord dat klopt?',
    ],
    dilemma: true,
  },
  {
    id: 'raadseltijd',
    title: 'Windy’s raadselbox',
    emoji: '🤔',
    category: 'raadsels',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain: 'De spelleider leest de raadsels één voor één voor. Jullie krijgen één antwoord per raadsel. Hoeveel raden jullie er?',
    list: {
      title: 'Raadsels (antwoorden enkel voor de spelleider)',
      items: {
        makkelijk: [
          'Wat heeft tanden maar kan niet bijten? (een kam)',
          'Wat wordt natter hoe meer het droogt? (een handdoek)',
          'Wat heeft een nek maar geen hoofd? (een fles)',
          'Wat loopt maar heeft geen benen? (water, een neus, een klok)',
          'Wat heeft vier poten maar kan niet lopen? (een tafel of stoel)',
          'Wat is er altijd voor je, maar kan je nooit zien? (de toekomst)',
          'Welk dier draagt zijn huis op zijn rug? (een slak of schildpad)',
        ],
        normaal: [
          'Wat heeft toetsen maar kan geen deur openen? (een piano of toetsenbord)',
          'Hoe meer je ervan neemt, hoe meer je achterlaat. (voetstappen)',
          'Wat breekt als je het zegt? (stilte)',
          'Wat gaat omhoog maar nooit omlaag? (je leeftijd)',
          'Wat heeft steden maar geen huizen, bossen maar geen bomen? (een landkaart)',
          'Wat kan je vangen maar niet gooien? (een verkoudheid)',
          'Wat heeft een hoofd en een staart maar geen lijf? (een munt)',
        ],
        pittig: [
          'Ik spreek zonder mond en hoor zonder oren. Wat ben ik? (een echo)',
          'De vader van Emma heeft vijf dochters: Nana, Nene, Nini, Nono. Hoe heet de vijfde? (Emma)',
          'Wat is zwaarder: een kilo veren of een kilo stenen? (even zwaar)',
          'Wat kan je nooit eten als ontbijt? (middageten en avondeten)',
          'Hoe kan iemand acht dagen niet slapen? (hij slaapt ’s nachts)',
          'Wat komt één keer voor in een minuut, twee keer in een moment, maar nooit in duizend jaar? (de letter M)',
          'Wat wordt groter hoe meer je eruit weghaalt? (een gat)',
        ],
      },
      pick: 5,
      secret: true,
    },
    scoring: { type: 'aantal', target: 5, unit: 'raadsels' },
    sabotage: [
      'Zeg één of twee keer als eerste een fout antwoord en leg uit waarom het klopt.',
      'Begin over iets anders te praten als iemand het goede antwoord bijna heeft.',
      'Zeg één keer "dat kan niet kloppen" als iemand het goede antwoord geeft.',
    ],
    detective: [
      'Let op wie vaak als eerste een fout antwoord roept.',
      'Wie zegt dat een goed antwoord niet kan kloppen?',
      'Wie begint over iets anders als iemand het antwoord bijna heeft?',
    ],
  },

  // ─────────────── Samenwerken ───────────────
  {
    id: 'bekertoren',
    title: 'De bekertoren',
    emoji: '🥤',
    category: 'samenwerken',
    locations: ['binnen', 'tuin'],
    supplies: ['plastiekbekers'],
    minPlayers: 3,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Bouw samen een piramide van bekers met {lagen} lagen. Maar let op: iedereen mag maar één hand gebruiken, en je andere hand hou je op je rug!',
    vars: { lagen: { makkelijk: [3], normaal: [4], pittig: [5] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Zet je beker net niet helemaal recht.',
      'Stel voor om de onderste bekers net iets te ver uit elkaar te zetten.',
      'Neem net iets te lang de tijd voor jouw beker als de klok bijna om is.',
    ],
    detective: [
      'Kijk wie zijn of haar beker scheef of wiebelig neerzet.',
      'Wie geeft bouwtips waardoor het moeilijker wordt?',
      'Wie treuzelt als de tijd bijna om is?',
    ],
    dilemma: true,
    photo: 'De toren met de bouwers eromheen.',
  },
  {
    id: 'tel-tot-twintig',
    title: 'Tel tot twintig',
    emoji: '🔢',
    category: 'samenwerken',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 5,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Ga in een kring staan en doe je ogen dicht. Tel samen tot {doel}, maar zonder af te spreken wie wat zegt. Iedereen mag op elk moment het volgende getal zeggen. Zeggen twee mensen tegelijk iets? Dan begin je opnieuw bij 1!',
    vars: { doel: { makkelijk: [12], normaal: [20], pittig: [25] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Zeg één of twee keer een getal net tegelijk met iemand anders.',
      'Zijn jullie bijna aan het doel? Zeg dan het volgende getal net iets te snel.',
      'Doe één keer alsof je je vergist en zeg een getal dat al geweest is.',
    ],
    detective: [
      'Luister goed: welke stem zegt vaak iets tegelijk met een ander?',
      'Wie praat er net mee als jullie bijna aan het doel zijn?',
      'Wie zegt een getal dat al geweest is?',
    ],
  },
  {
    id: 'mensenknoop',
    title: 'De mensenknoop',
    emoji: '🪢',
    category: 'samenwerken',
    locations: OVERAL,
    supplies: [],
    minPlayers: 4,
    minutes: 6,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Ga in een kring staan, steek je handen in het midden en neem twee willekeurige handen vast (niet van je buren). Nu zitten jullie in de knoop! Ontwar de knoop tot een kring zonder los te laten. Rustig en voorzichtig: niemand mag pijn hebben.',
    scoring: { type: 'gelukt' },
    sabotage: [
      'Laat één keer "per ongeluk" even los en neem snel weer vast.',
      'Stel één of twee keer een beweging voor die de knoop net moeilijker maakt.',
      'Beweeg net iets trager dan nodig, alsof je heel voorzichtig doet.',
    ],
    detective: [
      'Kijk naar de handen: wie laat er even los?',
      'Wie stelt bewegingen voor waardoor de knoop erger wordt?',
      'Wie beweegt opvallend traag als het bijna lukt?',
    ],
    photo: 'De knoop op het moeilijkste moment.',
  },
  {
    id: 'kranteneiland',
    title: 'Het kranteneiland',
    emoji: '📰',
    category: 'samenwerken',
    locations: ['binnen', 'tuin', 'park'],
    supplies: ['krantenpapier'],
    minPlayers: 3,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Leg een open krant op de grond. De hele groep moet erop staan, 5 tellen lang, zonder de grond te raken. Lukt het? Dan wordt de krant dubbelgevouwen. Hoeveel keer kunnen jullie de krant vouwen? Doel: {doel} keer.',
    vars: { doel: { makkelijk: [2], normaal: [3], pittig: [4] } },
    scoring: { type: 'aantal', target: '{doel}', unit: 'keer gevouwen' },
    sabotage: [
      'Zet als niemand kijkt je teen net naast de krant.',
      'Stel een "slimme" houding voor die eigenlijk meer plaats inneemt.',
      'Tel de 5 tellen luidop net iets trager mee dan de rest.',
    ],
    detective: [
      'Kijk naar de voeten: staat er een teen net naast de krant?',
      'Wie stelt een houding voor die meer plaats inneemt?',
      'Wie telt de tellen trager dan de rest?',
    ],
    photo: 'Iedereen samen op het kleinste stukje krant.',
  },
  {
    id: 'tapijt-omdraaien',
    title: 'Het vliegende tapijt',
    emoji: '🧞',
    category: 'samenwerken',
    locations: ['binnen', 'tuin', 'park', 'strand'],
    supplies: ['handdoeken'],
    minPlayers: 3,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Iedereen gaat op een grote handdoek of deken staan: dat is jullie vliegende tapijt. Draai het tapijt helemaal om, zonder dat iemand de grond raakt!',
    scoring: { type: 'gelukt' },
    sabotage: [
      'Zet als niemand kijkt een voet net naast het tapijt.',
      'Ga net op het stuk staan dat omgedraaid moet worden.',
      'Stel één keer een plan voor dat net niet werkt, zoals van twee kanten tegelijk beginnen.',
    ],
    detective: [
      'Kijk wie er net staat waar het tapijt omgevouwen moet worden.',
      'Let op voeten die "per ongeluk" de grond raken.',
      'Wie komt met een plan dat alles ingewikkelder maakt?',
    ],
    photo: 'Het tapijt halverwege het omdraaien.',
  },
  {
    id: 'hoepelketting',
    title: 'De hoepelketting',
    emoji: '⭕',
    category: 'samenwerken',
    locations: ['binnen', 'tuin', 'park', 'strand'],
    supplies: ['hoepels'],
    minPlayers: 4,
    minutes: 5,
    timer: 120,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Vorm een kring en geef elkaar een hand. De hoepel hangt over één paar armen. Laat de hoepel de hele kring rondgaan, over iedereen heen, zonder los te laten. Lukt het {rondes} keer rond binnen de tijd?',
    vars: { rondes: { makkelijk: [1], normaal: [2], pittig: [3] } },
    scoring: { type: 'aantal', target: '{rondes}', unit: 'rondes' },
    sabotage: [
      'Laat één keer even los als niemand kijkt.',
      'Hou je armen net wat te stijf, zodat de hoepel even blijft haken.',
      'Neem net iets langer de tijd als de hoepel bij jou is.',
    ],
    detective: [
      'Kijk goed naar de handen: blijft iedereen vasthouden?',
      'Bij wie blijft de hoepel opvallend vaak haken?',
      'Wie doet er lang over als de hoepel bij hem of haar is?',
    ],
  },

  // ─────────────── Geheugen ───────────────
  {
    id: 'dienblad',
    title: 'Het dienblad',
    emoji: '🧠',
    category: 'geheugen',
    locations: ['binnen', 'tuin'],
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Leg {aantal} verschillende voorwerpen uit huis op een dienblad of tafel en dek ze af met een doek.',
    explain:
      'Onder de doek liggen {aantal} voorwerpen. Jullie mogen 1 minuut kijken. Daarna draaien jullie je om en haalt de spelleider er één weg. Welk voorwerp is weg? Dat doen we 3 rondes.',
    vars: { aantal: { makkelijk: [8], normaal: [12], pittig: [16] } },
    scoring: { type: 'aantal', target: 3, unit: 'rondes juist' },
    sabotage: [
      'Roep één keer snel een voorwerp dat er nog gewoon ligt.',
      'Twijfel luidop als iemand het juiste antwoord zegt.',
      'Zeg dat er volgens jou nog een ander voorwerp lag, dat er nooit was.',
    ],
    detective: [
      'Let op wie snel een fout voorwerp roept.',
      'Wie maakt de groep onzeker als het antwoord goed is?',
      'Wie herinnert zich voorwerpen die er nooit lagen?',
    ],
  },
  {
    id: 'ik-ga-op-reis',
    title: 'Windy gaat op reis',
    emoji: '🧳',
    category: 'geheugen',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Windy gaat op reis en neemt mee... De eerste zegt: "Windy neemt haar pruik mee." De volgende herhaalt dat en voegt er iets aan toe. Zo gaat het rond. Hoe lang wordt de koffer? Doel: {doel} dingen zonder fout.',
    vars: { doel: { makkelijk: [8], normaal: [12], pittig: [16] } },
    scoring: { type: 'aantal', target: '{doel}', unit: 'dingen' },
    sabotage: [
      'Vergeet één keer "per ongeluk" iets in het midden.',
      'Voeg iets toe dat lijkt op iets dat al in de koffer zit, zoals sokken en kousen.',
      'Wissel één keer de volgorde van twee dingen.',
    ],
    detective: [
      'Luister wie dingen vergeet of van plaats wisselt.',
      'Wie voegt iets toe dat bijna hetzelfde is als iets anders in de koffer?',
      'Wie maakt een fout als de koffer bijna vol is?',
    ],
  },
  {
    id: 'patroon',
    title: 'Het klappatroon',
    emoji: '👏',
    category: 'geheugen',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 5,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De spelleider doet een patroon voor met klappen, stampen en knippen. De hele groep doet het tegelijk na. Elke ronde wordt het langer. Hoeveel rondes lukken jullie? Doel: {doel}.',
    vars: { doel: { makkelijk: [4], normaal: [6], pittig: [8] } },
    scoring: { type: 'aantal', target: '{doel}', unit: 'rondes' },
    sabotage: [
      'Klap één keer net een tel te vroeg, zodat anderen twijfelen.',
      'Doe één stukje verkeerd, zoals stampen in plaats van knippen.',
      'Vraag na het voordoen: "Eerst stampen, toch?" als het eerst klappen is.',
    ],
    detective: [
      'Kijk wie net te vroeg of te laat klapt.',
      'Wie stampt of knipt op het verkeerde moment?',
      'Wie zaait twijfel over hoe het patroon ging?',
    ],
  },

  // ─────────────── Behendigheid ───────────────
  {
    id: 'ballonnen-hooghouden',
    title: 'Ballonnen in de lucht',
    emoji: '🎈',
    category: 'behendigheid',
    locations: ['binnen', 'tuin'],
    supplies: ['ballonnen'],
    minPlayers: 3,
    minutes: 5,
    timer: 60,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Hou {aantal} ballonnen tegelijk in de lucht, een volle minuut lang. Niemand mag dezelfde ballon twee keer na elkaar aantikken. Valt er een ballon op de grond, dan is het mislukt!',
    vars: { aantal: { makkelijk: [2], normaal: [3], pittig: [4] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Tik een ballon net iets te hard, richting een hoek.',
      'Wacht net te lang met tikken, alsof je dacht dat iemand anders hem had.',
      'Roep één keer "ik heb hem!" en mis hem dan toch.',
    ],
    detective: [
      'Wie tikt ballonnen naar hoeken waar niemand staat?',
      'Wie roept "ik heb hem!" en mist dan toch?',
      'Wie blijft staan kijken als een ballon naar beneden zakt?',
    ],
    photo: 'Iedereen springend naar een ballon.',
  },
  {
    id: 'lepelrace',
    title: 'De lepelrace',
    emoji: '🥄',
    category: 'behendigheid',
    locations: ['binnen', 'tuin', 'park'],
    supplies: ['lepels', 'tennisballen'],
    minPlayers: 3,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Estafette! Draag een tennisbal op een lepel naar de overkant en terug, en geef hem door. Valt de bal? Dan begin je opnieuw vanaf de start. Komt iedereen aan de beurt voor de tijd om is?',
    scoring: { type: 'gelukt' },
    sabotage: [
      'Wandel net iets trager dan nodig, alsof je heel voorzichtig bent.',
      'Laat de bal één keer "per ongeluk" vallen, liefst bijna aan de overkant.',
      'Geef de lepel wat onhandig door, zodat de bal bijna valt.',
    ],
    detective: [
      'Wie loopt opvallend traag zonder dat het nodig is?',
      'Bij wie valt de bal net als het bijna gelukt is?',
      'Kijk goed hoe iedereen de lepel doorgeeft.',
    ],
    photo: 'De concentratie van de lepelrace.',
  },
  {
    id: 'mikken-emmer',
    title: 'Mikken maar!',
    emoji: '🎯',
    category: 'behendigheid',
    locations: ['tuin', 'park', 'bos', 'strand'],
    supplies: ['emmers', 'tennisballen'],
    minPlayers: 3,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Zet de emmer op {afstand} grote stappen. Iedereen mag {worpen} keer gooien. Samen moeten jullie {doel} ballen in de emmer krijgen.',
    vars: {
      afstand: { makkelijk: [4], normaal: [6], pittig: [8] },
      worpen: { normaal: [3] },
      doel: { makkelijk: [4], normaal: [6], pittig: [8] },
    },
    scoring: { type: 'aantal', target: '{doel}', unit: 'ballen' },
    sabotage: [
      'Gooi net iets te ver of te kort.',
      'Geef een mikadvies dat niet helpt, zoals "gooi harder" als het al te ver is.',
      'Tel de ballen in de emmer één keer verkeerd, eentje te weinig.',
    ],
    detective: [
      'Let op wie telkens net naast gooit.',
      'Wie geeft mikadvies waarna het slechter gaat?',
      'Tel zelf ook mee hoeveel ballen erin zitten.',
    ],
  },
  {
    id: 'balcirkel',
    title: 'De balcirkel',
    emoji: '⚽',
    category: 'behendigheid',
    locations: RUSTIG_BUITEN,
    supplies: ['bal'],
    minPlayers: 3,
    minutes: 5,
    timer: 120,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Ga in een grote kring staan. Gooi de bal naar elkaar en roep telkens de naam van wie je gooit. Niet naar je buren! Valt de bal, dan begint het tellen opnieuw. Halen jullie {doel} worpen na elkaar?',
    vars: { doel: { makkelijk: [10], normaal: [20], pittig: [30] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Roep één keer de verkeerde naam als je gooit, alsof je je vergist.',
      'Gooi net iets te hoog.',
      'Gooi naar iemand die net even niet oplet.',
    ],
    detective: [
      'Luister of de naam die geroepen wordt klopt met wie de bal krijgt.',
      'Wie gooit net te hoog of te ver?',
      'Wie gooit naar iemand die net niet kijkt?',
    ],
  },
  {
    id: 'papieren-vliegtuig',
    title: 'De vliegtuigfabriek',
    emoji: '✈️',
    category: 'behendigheid',
    locations: ['binnen', 'tuin'],
    supplies: ['papier'],
    minPlayers: 3,
    minutes: 8,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Iedereen vouwt een papieren vliegtuig. Daarna gooit iedereen om de beurt vanaf een lijn. Een vliegtuig telt als het verder dan {afstand} grote stappen landt. Doel: {doel} vliegtuigen.',
    vars: { afstand: { makkelijk: [3], normaal: [4], pittig: [5] }, doel: { makkelijk: [2], normaal: [3], pittig: [4] } },
    scoring: { type: 'aantal', target: '{doel}', unit: 'vliegtuigen' },
    sabotage: [
      'Vouw je vliegtuig net scheef.',
      'Geef anderen een "handige" vouwtip die niet werkt.',
      'Gooi je vliegtuig net iets te hard of te schuin omhoog.',
    ],
    detective: [
      'Kijk welk vliegtuig er opvallend scheef uitziet.',
      'Wie geeft vouwtips waarna het vliegtuig slecht vliegt?',
      'Wie gooit zijn of haar vliegtuig vreemd weg?',
    ],
    photo: 'Alle vliegtuigen klaar voor vertrek.',
  },

  // ─────────────── Creatief ───────────────
  {
    id: 'uitbeelden',
    title: 'Uitbeelden',
    emoji: '🎭',
    category: 'creatief',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Eén iemand beeldt uit, zonder te praten of geluid te maken. De rest raadt. Is het geraden? Dan beeldt de volgende het volgende woord uit. Hoeveel woorden raden jullie voor de tijd om is?',
    roles: [{ name: 'Eerste uitbeelder', count: 1, hint: 'Bekijk het eerste woord stiekem op de tablet.' }],
    list: {
      title: 'Uitbeeldwoorden',
      items: {
        makkelijk: ['olifant', 'tandenpoetsen', 'fietsen', 'kikker', 'zwemmen', 'slapen', 'voetbal', 'ijsje eten', 'vliegtuig', 'hond', 'aap', 'dansen'],
        normaal: ['astronaut', 'pannenkoeken bakken', 'brandweerman', 'pinguïn', 'skiën', 'tandarts', 'een ballon opblazen', 'kapper', 'koe melken', 'surfen', 'dinosaurus', 'selfie nemen', 'regen', 'schaatsen', 'piraat'],
        pittig: ['vulkaan', 'onweer', 'bakker die zich verbrandt', 'spin in een web', 'windmolen', 'lift die vastzit', 'kampvuur', 'verliefd zijn', 'wasmachine', 'toverstaf', 'Windy haar pruik', 'jaloers zijn', 'kermis'],
      },
      pick: 10,
      secret: true,
      turns: true,
    },
    scoring: { type: 'aantal', target: 6, unit: 'woorden' },
    sabotage: [
      'Raad één of twee keer fout, maar met veel enthousiasme.',
      'Beeld zelf een beetje vaag uit, alsof je het moeilijk vindt.',
      'Roep een fout antwoord net als iemand anders het goede zegt.',
    ],
    detective: [
      'Wie beeldt opvallend vaag uit, terwijl het woord makkelijk is?',
      'Wie roept iets fout net als iemand anders het goede antwoord zegt?',
      'Wie raadt telkens net naast het antwoord?',
    ],
    photo: 'De grappigste uitbeelding.',
  },
  {
    id: 'blind-tekenen',
    title: 'Blind tekenen',
    emoji: '✏️',
    category: 'creatief',
    locations: ['binnen', 'tuin'],
    supplies: ['papier', 'stiften'],
    minPlayers: 3,
    minutes: 8,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De Verteller leest stiekem een tekening op de tablet en legt uit wat de anderen moeten tekenen, zonder de naam van het ding te zeggen. De tekenaars mogen niets vragen! Daarna vergelijken jullie. Lijkt het genoeg? Dan is het gelukt.',
    roles: [{ name: 'Verteller', count: 1, hint: 'Lees de tekening stiekem op de tablet.' }],
    list: {
      title: 'Wat moeten ze tekenen?',
      items: {
        makkelijk: ['Een huis met een rode deur, twee ramen en een zon linksboven.', 'Een grote boom met drie appels en een vogel ernaast.', 'Een smiley met een hoed.'],
        normaal: ['Een huis met een schoorsteen die rookt, een boom rechts en een wolk boven het huis.', 'Een kat die op een stoel zit, met een bal onder de stoel.', 'Een raket met drie ramen die naar de maan vliegt.'],
        pittig: ['Een zeilboot op golven, met een zon half achter een wolk en een vis die uit het water springt.', 'Windy met haar pruik, die met haar ene hand zwaait en met de andere een pannenkoek vasthoudt.', 'Een kasteel met twee torens, een vlag op de linkertoren en een brug over een gracht.'],
      },
      pick: 1,
      secret: true,
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Als Verteller: zeg één keer links en rechts verkeerd om.',
      'Teken één ding op de verkeerde plek, alsof je het slecht verstaan hebt.',
      'Voeg stiekem iets kleins toe dat er niet bij hoort.',
    ],
    detective: [
      'Luister goed: klopt wat de Verteller zegt met de tekening achteraf?',
      'Wiens tekening heeft iets op een rare plek?',
      'Kijk wie dingen tekent die niemand gezegd heeft.',
    ],
    photo: 'Alle tekeningen naast elkaar.',
  },
  {
    id: 'rijmrap',
    title: 'De Windy-rap',
    emoji: '🎤',
    category: 'creatief',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Maak samen een rap van {regels} zinnen over {onderwerp}. De zinnen moeten rijmen! Daarna voeren jullie hem op voor de spelleider, met beat (klappen of stampen).',
    vars: {
      regels: { makkelijk: [2], normaal: [4], pittig: [6] },
      onderwerp: { normaal: ['de jarige', 'Windy haar pruik', 'onzen Kenzo', "'t Duvelke", 'pannenkoeken', 'de schatkist'] },
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Stel één keer een woord voor dat bijna rijmt, maar net niet.',
      'Vergeet een stukje van je zin op het moment van optreden.',
      'Klap of stamp af en toe net uit de maat.',
    ],
    detective: [
      'Wie komt met woorden die net niet rijmen?',
      'Wie is zijn of haar zin kwijt bij het optreden?',
      'Luister wie de beat net verkeerd klapt of stampt.',
    ],
    photo: 'De rappers in hun stoerste pose.',
  },
  {
    id: 'stoepkrijt-kunst',
    title: 'Het krijtkunstwerk',
    emoji: '🖍️',
    category: 'creatief',
    locations: ['straat', 'tuin', 'park'],
    supplies: ['stoepkrijt'],
    minPlayers: 3,
    minutes: 10,
    timer: 360,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Teken samen één groot kunstwerk met stoepkrijt over het thema "{thema}". Het moet minstens deze dingen bevatten: {dingen}. Enkel op de stoep of het terras, nooit op de rijweg!',
    vars: {
      thema: { normaal: ['een schattenjacht', 'de verjaardag', 'de onderwaterwereld', 'Windy’s droomhuis', 'de ruimte'] },
      dingen: { makkelijk: ['een zon, een dier en een hart'], normaal: ['een zon, drie dieren, een schatkist en iedereens naam'], pittig: ['een zon, vijf dieren, een schatkist, een geheime code en iedereens handtekening'] },
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Teken iets dat maar half bij het thema past.',
      'Neem veel tijd voor je eigen kleine stukje.',
      'Zeg dat een verplicht ding al getekend is, ook als het er nog niet staat.',
    ],
    detective: [
      'Wie tekent dingen die niet goed bij het thema passen?',
      'Wie is nog altijd bezig met hetzelfde kleine stukje?',
      'Check zelf de lijst: staat alles er echt op?',
    ],
    photo: 'Het kunstwerk van bovenaf.',
  },
  {
    id: 'zandkasteel',
    title: 'Het zandkasteel',
    emoji: '🏰',
    category: 'creatief',
    locations: ['strand'],
    supplies: ['schepjes', 'emmers'],
    minPlayers: 3,
    minutes: 12,
    timer: 480,
    difficulties: [...ALLE_NIVEAUS],
    explain: 'Bouw samen een kasteel met {torens} torens, een gracht en een poort. Het moet nog rechtstaan als de tijd om is!',
    vars: { torens: { makkelijk: [2], normaal: [4], pittig: [6] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Graaf de gracht net te dicht bij een toren.',
      'Gebruik droog zand voor jouw toren.',
      'Stel voor om het kasteel nog groter te maken als de tijd bijna om is.',
    ],
    detective: [
      'Wiens toren zakt telkens in?',
      'Wie graaft de gracht heel dicht bij de torens?',
      'Wie wil op het einde nog extra bouwen?',
    ],
    photo: 'De bouwers achter hun kasteel.',
  },

  // ─────────────── Quiz ───────────────
  {
    id: 'windy-quiz',
    title: 'Windy’s superquiz',
    emoji: '❓',
    category: 'quiz',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Windy stelt {aantal} vragen. Overleg samen en kies één antwoord. De tablet telt zelf de punten. Maar pas op: wie hard roept, heeft niet altijd gelijk!',
    vars: { aantal: { normaal: [8] } },
    scoring: { type: 'quiz', questions: 8 },
    sabotage: [
      'Zeg één of twee keer heel zeker een fout antwoord.',
      'Zeg "dat weet ik uit school!" bij een fout antwoord.',
      'Twijfel luidop bij een goed antwoord, zodat de groep van mening verandert.',
    ],
    detective: [
      'Wie is heel zeker van antwoorden die fout blijken?',
      'Wie doet de groep twijfelen bij een goed antwoord?',
      'Onthoud wie welk antwoord voorstelde en kijk wat juist was.',
    ],
  },
  {
    id: 'dieren-alfabet',
    title: 'Het dierenalfabet',
    emoji: '🦒',
    category: 'quiz',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 5,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Noem om de beurt een dier, in volgorde van het alfabet: A van aap, B van beer... Weet je het niet, dan mag de groep helpen. Hoe ver komen jullie? Doel: letter {letter}.',
    vars: { letter: { makkelijk: ['K'], normaal: ['P'], pittig: ['W'] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Denk één keer heel lang na, ook als je het weet.',
      'Noem één keer een dier dat goed klinkt maar met een andere letter begint, zoals cavia bij de K.',
      'Geef een hulpje dat niet klopt als iemand vastzit.',
    ],
    detective: [
      'Wie denkt lang na bij een makkelijke letter?',
      'Klopt de eerste letter van elk dier echt?',
      'Wie helpt met een dier dat niet bij de letter past?',
    ],
  },
  {
    id: 'woordslang',
    title: 'De woordslang',
    emoji: '🐍',
    category: 'quiz',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 5,
    timer: 120,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Zeg om de beurt een woord uit het thema "{thema}". Je woord moet beginnen met de laatste letter van het vorige woord. Geen dubbels! Hoeveel woorden halen jullie? Doel: {doel}.',
    vars: {
      thema: { makkelijk: ['eten'], normaal: ['dieren', 'eten', 'dingen in huis'], pittig: ['landen en steden', 'beroepen'] },
      doel: { makkelijk: [8], normaal: [12], pittig: [15] },
    },
    scoring: { type: 'aantal', target: '{doel}', unit: 'woorden' },
    sabotage: [
      'Zeg één keer een woord dat al gezegd is, alsof je het vergeten was.',
      'Kies een woord dat eindigt op een moeilijke letter, zoals een z, een y of een u.',
      'Neem veel bedenktijd.',
    ],
    detective: [
      'Wie eindigt opvallend vaak op een moeilijke letter?',
      'Hou in je hoofd bij welke woorden al gezegd zijn.',
      'Wie heeft veel bedenktijd nodig bij een makkelijke letter?',
    ],
  },

  // ─────────────── Communicatie ───────────────
  {
    id: 'blinde-piloot',
    title: 'De blinde piloot',
    emoji: '🙈',
    category: 'communicatie',
    locations: ['binnen', 'tuin', 'park'],
    supplies: ['blinddoek', 'knuffels'],
    minPlayers: 3,
    minutes: 7,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Leg een knuffel ergens in de ruimte, op een veilige plek zonder trappen of scherpe hoeken.',
    explain:
      'De Piloot krijgt een blinddoek. De rest mag enkel met woorden de weg wijzen naar de knuffel: vooruit, stop, links, rechts. Niemand mag de Piloot aanraken. Brengt de Piloot de knuffel terug naar de start? Voorzichtig en traag!',
    roles: [{ name: 'Piloot', count: 1, hint: 'Doe de blinddoek om.' }],
    scoring: { type: 'gelukt' },
    sabotage: [
      'Zeg één keer links als het rechts moet zijn, en verbeter je daarna snel.',
      'Praat net door iemand anders heen.',
      'Zeg "stop" net een stapje te vroeg, zodat de Piloot de knuffel mist.',
    ],
    detective: [
      'Luister wie links en rechts door elkaar haalt.',
      'Wie praat er door de anderen heen?',
      'Wie laat de Piloot net te vroeg stoppen?',
    ],
    photo: 'De piloot met blinddoek en de knuffel.',
  },
  {
    id: 'fluisterketting',
    title: 'De fluisterketting',
    emoji: '👂',
    category: 'communicatie',
    locations: OVERAL,
    supplies: [],
    minPlayers: 4,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De Eerste leest stiekem een zin op de tablet en fluistert die in het oor van de volgende. Zo gaat het rij rond. De laatste zegt de zin luidop. Is hij bijna hetzelfde? Dan is het gelukt. We doen 3 zinnen.',
    roles: [{ name: 'Eerste', count: 1, hint: 'Lees de zin stiekem op de tablet.' }],
    list: {
      title: 'Fluisterzinnen',
      items: {
        makkelijk: ['Windy eet graag pannenkoeken.', 'De kat zit op het dak.', 'Kenzo slaapt nog.', 'Mijn pruik is zwart.'],
        normaal: ['Windy heeft haar pruik in de soep laten vallen.', 'Onzen Kenzo heeft zeven sokken onder zijn bed.', 'De buurvrouw weet altijd alles eerst.', 'Een giraf met een sjaal eet een ijsje.'],
        pittig: ['Zeven zotte zeehonden zwemmen zingend naar Zeeland.', 'Windy’s buurvrouw bakt bruine broodjes met blauwe bessen.', 'Kenzo kocht krokante koekjes in de Kempen.', 'Achtentachtig acrobaten aten appeltaart.'],
      },
      pick: 3,
      secret: true,
      turns: true,
    },
    scoring: { type: 'aantal', target: 3, unit: 'zinnen' },
    sabotage: [
      'Verander één woord een beetje als je doorfluistert.',
      'Fluister net iets te zacht of te snel.',
      'Doe alsof je het niet goed verstaan hebt.',
    ],
    detective: [
      'Vraag na afloop zacht aan je buur wat die gehoord heeft.',
      'Op welke plek in de rij veranderde de zin?',
      'Wie fluistert zo zacht dat je het amper hoort?',
    ],
  },
  {
    id: 'blind-bouwen',
    title: 'De bouwmeester',
    emoji: '🧱',
    category: 'communicatie',
    locations: ['binnen'],
    supplies: ['legoblokjes'],
    minPlayers: 3,
    minutes: 8,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Bouw in het geheim een klein bouwwerkje van {blokjes} blokjes en zet het uit het zicht. Leg dezelfde blokjes klaar voor de groep.',
    explain:
      'De Bouwmeester mag het geheime bouwwerk gaan bekijken, maar niet aanraken. Daarna legt de Bouwmeester uit hoe de rest het moet nabouwen, zonder zelf blokjes aan te raken. Lijkt het precies? Dan is het gelukt.',
    vars: { blokjes: { makkelijk: [5], normaal: [8], pittig: [12] } },
    roles: [{ name: 'Bouwmeester', count: 1, hint: 'Ga het geheime bouwwerk bekijken.' }],
    scoring: { type: 'gelukt' },
    sabotage: [
      'Als Bouwmeester: zeg één kleur verkeerd, alsof je je vergiste.',
      'Bouw jouw stukje net verkeerd om.',
      'Stel een vraag net als de Bouwmeester iets belangrijks uitlegt.',
    ],
    detective: [
      'Vergelijk achteraf: welke kleur of welk blokje klopte er niet?',
      'Kijk wie een blokje net anders neerlegt dan gezegd.',
      'Wie onderbreekt de Bouwmeester vaak?',
    ],
    photo: 'Het origineel naast de kopie.',
  },

  // ─────────────── Tijdsdruk ───────────────
  {
    id: 'sokkenchaos',
    title: 'Sokkenchaos',
    emoji: '🧦',
    category: 'tijdsdruk',
    locations: ['binnen'],
    supplies: ['sokken', 'wasmand'],
    minPlayers: 3,
    minutes: 5,
    timer: 90,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Gooi {paren} paar sokken door elkaar in een wasmand.',
    explain: 'Oei, de was van onzen Kenzo! Zoek zo snel mogelijk alle {paren} paren sokken bij elkaar en rol ze op.',
    vars: { paren: { makkelijk: [6], normaal: [10], pittig: [14] } },
    scoring: { type: 'aantal', target: '{paren}', unit: 'paren' },
    sabotage: [
      'Maak een paar met twee sokken die net niet hetzelfde zijn.',
      'Rol één keer een sok op zonder partner.',
      'Zoek lang naar de partner van een sok die al opgerold is.',
    ],
    detective: [
      'Kijk na of de opgerolde paren echt bij elkaar horen.',
      'Wie rolt een sok op zonder dat er een tweede bij zit?',
      'Wie zoekt lang zonder iets te vinden?',
    ],
    photo: 'De stapel opgerolde sokken.',
  },
  {
    id: 'tijdbom',
    title: 'De tijdbom',
    emoji: '💣',
    category: 'tijdsdruk',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 6,
    timer: 60,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De tijdbom tikt! Noem samen binnen de minuut {doel} dingen die {soort}. De spelleider telt mee. Dubbels tellen niet!',
    vars: {
      doel: { makkelijk: [8], normaal: [12], pittig: [15] },
      soort: { normaal: ['geel zijn', 'in de keuken liggen', 'kunnen vliegen', 'je op een verjaardagsfeest vindt', 'rond zijn', 'in de zee leven'] },
    },
    scoring: { type: 'aantal', target: '{doel}', unit: 'dingen' },
    sabotage: [
      'Herhaal één keer iets dat al gezegd is, maar in andere woorden.',
      'Zeg iets dat er net niet bij hoort.',
      'Begin net te praten als iemand anders iets wil zeggen.',
    ],
    detective: [
      'Wie zegt dingen die al gezegd zijn?',
      'Klopt alles wat iemand roept echt bij de opdracht?',
      'Wie onderbreekt de anderen net op het verkeerde moment?',
    ],
  },
  {
    id: 'innerlijke-klok',
    title: 'De innerlijke klok',
    emoji: '⏱️',
    category: 'tijdsdruk',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 4,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Iedereen doet de ogen dicht. De spelleider start de klok. Roep samen "STOP!" als jullie denken dat er precies {seconden} seconden voorbij zijn. Niet luidop tellen! Zitten jullie er minder dan {marge} seconden naast, dan is het gelukt.',
    vars: { seconden: { makkelijk: [20], normaal: [30], pittig: [45] }, marge: { makkelijk: [4], normaal: [3], pittig: [2] } },
    scoring: { type: 'stopwatch', seconds: '{seconden}', margin: '{marge}' },
    sabotage: [
      'Roep net iets te vroeg "stop".',
      'Tik zachtjes met je voet op een snel ritme, zodat je buren sneller gaan tellen.',
      'Zucht één keer, alsof het al heel lang duurt.',
    ],
    detective: [
      'Wie roept "stop" net voor de rest?',
      'Hoor je iemand tikken of zuchten tijdens het wachten?',
      'Wie zegt achteraf dat het "zeker al tijd was"?',
    ],
  },

  // ─────────────── Speuren ───────────────
  {
    id: 'wat-is-veranderd',
    title: 'Wat is er veranderd?',
    emoji: '🕵️',
    category: 'speuren',
    locations: OVERAL,
    supplies: [],
    minPlayers: 4,
    minutes: 7,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De Detective kijkt 30 seconden goed naar de groep. Dan gaat de Detective even weg. De groep verandert {aantal} dingen aan zichzelf (bril af, mouw opgerold, plaats gewisseld). Vindt de Detective alle veranderingen?',
    vars: { aantal: { makkelijk: [2], normaal: [3], pittig: [5] } },
    roles: [{ name: 'Detective', count: 1, hint: 'Kijk goed naar iedereen.' }],
    scoring: { type: 'gelukt' },
    sabotage: [
      'Verander iets heel kleins dat bijna niet op te merken is.',
      'Verander stiekem nog iets extra, zodat het meer wordt dan afgesproken.',
      'Ga net achter iemand staan, zodat jouw verandering moeilijk te zien is.',
    ],
    detective: [
      'Wie verandert iets wat bijna niet te zien is?',
      'Tel na: zijn er meer veranderingen dan afgesproken?',
      'Wie gaat zo staan dat je hem of haar slecht ziet?',
    ],
  },
  {
    id: 'geluiden-raden',
    title: 'Wat hoor je?',
    emoji: '🔊',
    category: 'speuren',
    locations: ['binnen'],
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Zoek {aantal} voorwerpen die een geluid maken (sleutelbos, papier verfrommelen, lepel in een tas, rits...).',
    explain: 'Iedereen doet de ogen dicht. De spelleider maakt {aantal} geluiden. Overleg na elk geluid: wat was het? Doel: {doel} juist.',
    vars: { aantal: { normaal: [7] }, doel: { makkelijk: [4], normaal: [5], pittig: [6] } },
    scoring: { type: 'aantal', target: '{doel}', unit: 'geluiden' },
    sabotage: [
      'Zeg één keer snel en heel zeker een fout antwoord.',
      'Schuifel of kuch zachtjes net als een geluid begint.',
      'Zeg één keer "dat hebben we al gehad" bij een nieuw geluid.',
    ],
    detective: [
      'Wie is heel zeker van een antwoord dat fout is?',
      'Hoor je iemand kuchen of schuifelen net bij een geluid?',
      'Wie zegt dat een geluid al geweest is, terwijl het nieuw is?',
    ],
  },
  {
    id: 'spoorzoeker',
    title: 'De spoorzoeker',
    emoji: '👣',
    category: 'speuren',
    locations: ['tuin', 'bos', 'park'],
    supplies: ['wol'],
    minPlayers: 3,
    minutes: 10,
    timer: 420,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Knoop op voorhand {aantal} stukjes wol aan takken of struiken langs een route, en verstop op het einde een kleine verrassing.',
    explain: 'Volg het spoor van gekleurde wolletjes. Tel ze onderweg! Aan het einde vinden jullie iets. Vertel de spelleider hoeveel wolletjes er waren.',
    vars: { aantal: { makkelijk: [6], normaal: [10], pittig: [14] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Tel één keer luidop verkeerd, zodat de anderen twijfelen.',
      'Zeg dat je een wolletje ziet in de verkeerde richting.',
      'Tel een wolletje twee keer als jullie even terug moeten lopen.',
    ],
    detective: [
      'Tel zelf stil in je hoofd mee.',
      'Wie zag een wolletje waar er dan geen blijkt te zijn?',
      'Wie maakt de groep in de war over het aantal?',
    ],
    photo: 'De ontdekkingsreizigers bij de verrassing.',
  },

  // ─────────────── Foto ───────────────
  {
    id: 'fotoposes',
    title: 'Poseer als...',
    emoji: '📸',
    category: 'foto',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De spelleider noemt een pose. De hele groep heeft 10 tellen om samen die pose te vormen, zonder te praten! Dan maakt de spelleider een foto. Staat iedereen goed? Dan telt het.',
    list: {
      title: 'Poses',
      items: {
        normaal: ['een brug', 'een grote bloem', 'een auto met vier wielen', 'een verjaardagstaart', 'een draak', 'de letter H', 'een wasmachine', 'Windy haar pruik', 'een raket die opstijgt', 'een spin'],
      },
      pick: 5,
      secret: false,
    },
    scoring: { type: 'aantal', target: 5, unit: 'poses' },
    sabotage: [
      'Ga zo staan dat de vorm net een beetje scheef wordt.',
      'Beweeg één keer net als de foto genomen wordt.',
      'Trek één keer een grappig gezicht, zodat iemand moet lachen.',
    ],
    detective: [
      'Bekijk de foto’s: wie staat er telkens net verkeerd?',
      'Wie beweegt net als de foto gemaakt wordt?',
      'Wie probeert anderen aan het lachen te krijgen?',
    ],
    photo: 'De beste pose van allemaal.',
  },
  {
    id: 'reuzenwoord',
    title: 'Het reuzenwoord',
    emoji: '✍️',
    category: 'foto',
    locations: ['tuin', 'bos', 'park', 'strand'],
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain: 'Schrijf het woord "{woord}" zo groot mogelijk op de grond met takjes, blaadjes, steentjes of schelpen. Elke letter minstens zo groot als een voet!',
    vars: { woord: { makkelijk: ['WINDY', 'FEEST'], normaal: ['DUVELKE', 'SCHATKIST'], pittig: ['VERJAARDAG', 'SPEURNEUS'] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Leg één letter "per ongeluk" spiegelverkeerd, zoals een S of een N.',
      'Maak jouw letter net te klein of met te weinig spullen.',
      'Zeg dat een letter al klaar is, ook als er nog een stuk mist.',
    ],
    detective: [
      'Lees het woord letter per letter: staat alles goed?',
      'Wiens letter is te klein of te dun?',
      'Wie zegt dat iets klaar is als het nog niet af is?',
    ],
    photo: 'Het reuzenwoord van bovenaf, met iedereen erachter.',
  },

  // ─────────────── Beweging ───────────────
  {
    id: 'standbeelden',
    title: 'Windy’s standbeelden',
    emoji: '🗿',
    category: 'beweging',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 5,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De spelleider draait zich om en telt tot {tellen}. Dan mag iedereen bewegen, dansen of sluipen. Draait de spelleider zich om, dan moet iedereen stokstijf stilstaan. Wie beweegt, moet terug naar de start. Tikt iemand de spelleider aan binnen {rondes} rondes? Dan is het gelukt.',
    vars: { tellen: { normaal: [5] }, rondes: { makkelijk: [8], normaal: [6], pittig: [5] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Beweeg één keer "per ongeluk" net na het omdraaien.',
      'Trek een grappig gezicht als de anderen stil moeten staan.',
      'Sluip net iets trager dan nodig.',
    ],
    detective: [
      'Wie moet opvallend vaak terug naar de start?',
      'Wie probeert de anderen aan het lachen te brengen?',
      'Wie komt bijna nooit vooruit?',
    ],
  },
  {
    id: 'estafette-letters',
    title: 'Letterestafette',
    emoji: '🏃',
    category: 'beweging',
    locations: ['tuin', 'park', 'strand'],
    supplies: [],
    minPlayers: 3,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Markeer een start en een keerpunt op {afstand} grote stappen. Loop om de beurt naar het keerpunt en roep daar een woord met de letter "{letter}". Terug, tik de volgende aan. Geen dubbele woorden! Halen jullie {doel} woorden voor de tijd om is?',
    vars: {
      afstand: { makkelijk: [8], normaal: [10], pittig: [12] },
      letter: { normaal: ['B', 'K', 'S', 'P', 'M', 'T'] },
      doel: { makkelijk: [6], normaal: [10], pittig: [14] },
    },
    scoring: { type: 'aantal', target: '{doel}', unit: 'woorden' },
    sabotage: [
      'Vergeet één keer je woord aan het keerpunt en roep "euh...".',
      'Roep één keer een woord dat al gezegd is.',
      'Loop net iets trager.',
      'Tik de volgende net iets te laat aan.',
    ],
    detective: [
      'Wie staat aan het keerpunt opvallend lang na te denken?',
      'Hou in je hoofd bij welke woorden al geroepen zijn.',
      'Wie loopt trager dan je zou verwachten?',
    ],
  },
  {
    id: 'springtouw-samen',
    title: 'Samen springen',
    emoji: '🪢',
    category: 'beweging',
    locations: ['tuin', 'park', 'strand'],
    supplies: ['springtouw'],
    minPlayers: 4,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Twee mensen draaien het touw. De rest springt erin, één voor één, tot jullie met {springers} tegelijk springen. Houden jullie het {sprongen} sprongen vol?',
    vars: { springers: { makkelijk: [2], normaal: [3], pittig: [4] }, sprongen: { makkelijk: [3], normaal: [5], pittig: [8] } },
    roles: [{ name: 'Draaier', count: 2, hint: 'Draai het touw rustig en gelijk.' }],
    scoring: { type: 'gelukt' },
    sabotage: [
      'Als Draaier: draai het touw net iets te snel of te traag.',
      'Spring net iets te laat in.',
      'Roep één keer "nu!" op het verkeerde moment.',
    ],
    detective: [
      'Kijk of het touw mooi gelijk blijft draaien.',
      'Wie springt telkens net te laat in?',
      'Wie roept "nu!" op een moment dat het niet uitkomt?',
    ],
    photo: 'Iedereen tegelijk in de lucht.',
  },
];
