import type { LocationId } from '../types';
import type { TaskDef } from './types';

const OVERAL: LocationId[] = ['binnen', 'tuin', 'straat', 'bos', 'park', 'dorp', 'strand'];
const RUSTIG_BUITEN: LocationId[] = ['tuin', 'bos', 'park', 'strand'];
const BINNEN_TUIN: LocationId[] = ['binnen', 'tuin'];
const ALLE_NIVEAUS = ['makkelijk', 'normaal', 'pittig'] as const;

/**
 * De ingebouwde opdrachten. Sabotagetips zijn altijd stiekem en veilig:
 * nooit duwen, trekken, iets kapotmaken of iemand pijn doen.
 */
export const BUILTIN_TASKS: TaskDef[] = [
  // ─────────────── Zoeken ───────────────
  {
    id: 'wasknijper-jacht',
    title: 'De wasknijperjacht',
    emoji: '🪝',
    category: 'zoeken',
    locations: BINNEN_TUIN,
    supplies: ['wasknijpers'],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Verstop {aantal} wasknijpers (binnen of in de tuin) terwijl de groep niet kijkt.',
    explain:
      'Er zijn {aantal} wasknijpers verstopt! Zoek ze allemaal voor de tijd om is. Elke gevonden wasknijper breng je meteen naar de spelleider.',
    vars: { aantal: { makkelijk: [8], normaal: [12], pittig: [15] } },
    scoring: { type: 'aantal', target: '{aantal}', unit: 'wasknijpers' },
    sabotage: [
      'Vind je een wasknijper? Laat hem stiekem liggen en loop gewoon verder.',
      'Zeg dat je een plek al grondig doorzocht hebt, ook als dat niet zo is.',
      'Stuur de groep naar een kamer of hoek waar zeker niets ligt.',
    ],
    dilemma: true,
    photo: 'Iedereen met een wasknijper aan zijn oor.',
  },
  {
    id: 'kleurenjacht',
    title: 'Kleurenjacht',
    emoji: '🌈',
    category: 'zoeken',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Zoek zo snel mogelijk voorwerpen in deze kleuren en leg ze samen op één plek (buiten: wijs ze aan of maak een foto). Elke kleur telt één keer.',
    list: {
      title: 'Zoek iets dat...',
      items: {
        makkelijk: ['rood is', 'geel is', 'blauw is', 'groen is', 'wit is', 'zwart is', 'roze is', 'oranje is'],
        normaal: ['rood is', 'geel is', 'blauw is', 'groen is', 'paars is', 'oranje is', 'goud of zilver is', 'gestreept is', 'gestipt is', 'doorzichtig is'],
        pittig: ['lichtblauw is', 'donkergroen is', 'bruin én rond is', 'gestreept is', 'gestipt is', 'doorzichtig is', 'drie kleuren heeft', 'glanzend is', 'turquoise is', 'beige is'],
      },
      pick: 8,
      secret: false,
    },
    scoring: { type: 'aantal', target: 8, unit: 'kleuren' },
    sabotage: [
      'Kom af met iets dat bijna de goede kleur heeft en hou vol dat het klopt.',
      'Zoek heel traag en blijf lang op één plek staan kijken.',
      'Leg een gevonden voorwerp stiekem weer terug.',
    ],
    photo: 'Alle gevonden kleuren netjes op een rij.',
  },
  {
    id: 'natuurbingo',
    title: 'Natuurbingo',
    emoji: '🍂',
    category: 'zoeken',
    locations: ['bos', 'park', 'tuin'],
    supplies: [],
    minPlayers: 3,
    minutes: 10,
    timer: 420,
    difficulties: [...ALLE_NIVEAUS],
    explain: 'Verzamel alles van de bingokaart en breng het naar de spelleider. Enkel dingen die al op de grond liggen: niets afbreken!',
    list: {
      title: 'Bingokaart',
      items: {
        makkelijk: ['een dennenappel', 'een blad', 'een steentje', 'een takje', 'iets geels', 'een eikel of kastanje', 'iets zachts', 'iets ronds', 'iets bruins', 'een veer'],
        normaal: ['een dennenappel', 'een blad groter dan je hand', 'een helemaal rond steentje', 'een Y-vormig takje', 'een veer', 'iets dat lekker ruikt', 'drie verschillende bladeren', 'een eikel of kastanje', 'iets dat rood is', 'mos'],
        pittig: ['een blad met gekartelde rand', 'een steentje met een streep', 'een takje exact zo lang als je arm', 'een veer', 'vijf verschillende bladeren', 'iets dat een dier gegeten heeft', 'een platte steen', 'een dennenappel die nog dicht is', 'iets dat van een mens komt (afval)', 'mos'],
      },
      pick: 9,
      secret: false,
    },
    scoring: { type: 'aantal', target: 9, unit: 'vakjes' },
    sabotage: [
      'Breng iets mee dat niet helemaal klopt en zeg overtuigd dat het goed is.',
      'Loop steeds de verkeerde kant op en roep dat je daar iets zag.',
      'Laat iets dat al gevonden was stiekem vallen.',
    ],
    photo: 'De volle bingokaart met alle spullen.',
  },
  {
    id: 'speurlijst-buurt',
    title: 'Speurlijst in de buurt',
    emoji: '🏘️',
    category: 'zoeken',
    locations: ['straat', 'dorp'],
    supplies: [],
    minPlayers: 3,
    minutes: 12,
    timer: 600,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Wandel samen met de volwassene door de buurt en zoek alles van de lijst. Wijs het aan en roep het luid. Blijf altijd samen en op de stoep!',
    list: {
      title: 'Zoek in de buurt...',
      items: {
        normaal: ['een brievenbus', 'een huisnummer met een 7', 'een fiets met een mandje', 'een kat', 'een rode deur', 'een verkeersbord met een fiets', 'een tuinkabouter', 'iemand die een hond uitlaat', 'een huisnummer boven de 50', 'een bloembak', 'een raam met gordijnen met bloemen', 'een auto met een trekhaak'],
        pittig: ['een huisnummer met drie dezelfde cijfers', 'een straatnaam met een dierennaam', 'een blauwe auto met een fietsdrager', 'een deur met een klopper', 'een schoorsteen die rookt', 'een verkeersbord met een uitroepteken', 'een bel met drie namen', 'een tuinkabouter', 'een kat op een vensterbank', 'een winkel'],
      },
      pick: 8,
      secret: false,
    },
    scoring: { type: 'aantal', target: 8, unit: 'dingen' },
    sabotage: [
      'Zeg dat je iets gezien hebt als dat niet zo is, zodat de groep terugloopt.',
      'Treuzel een beetje, maar blijf wel altijd bij de groep.',
      'Twijfel luidop of iets wel echt telt.',
    ],
    photo: 'De hele groep bij het leukste ding van de lijst.',
  },
  {
    id: 'schelpenjacht',
    title: 'Schelpenjacht',
    emoji: '🐚',
    category: 'zoeken',
    locations: ['strand'],
    supplies: ['emmers'],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain: 'Verzamel samen {aantal} verschillende schelpen in de emmer. Elke soort telt maar één keer!',
    vars: { aantal: { makkelijk: [6], normaal: [10], pittig: [14] } },
    scoring: { type: 'aantal', target: '{aantal}', unit: 'soorten' },
    sabotage: ['Leg een schelp die er al in zat er nog eens in en zeg dat ze anders is.', 'Neem de emmer mee naar de verkeerde kant.', 'Kies steeds kapotte schelpjes.'],
    photo: 'Alle schelpen op een rij in het zand.',
  },

  // ─────────────── Raadsels ───────────────
  {
    id: 'codeslot',
    title: 'Het codeslot',
    emoji: '🔐',
    category: 'raadsels',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De schatkist zit op slot! Elk raadsel geeft één cijfer van de code. Los ze samen op en zeg de volledige code tegen de spelleider. Die kijkt of ze klopt.',
    list: {
      title: 'Raadsels (antwoorden enkel voor de spelleider)',
      items: {
        makkelijk: [
          'Hoeveel poten heeft een spin? (8)',
          'Hoeveel wielen heeft een driewieler? (3)',
          'Hoeveel dagen heeft een week? (7)',
          'Hoeveel ogen heeft een mens? (2)',
          'Hoeveel kleuren heeft de Belgische vlag? (3)',
          'Hoeveel poten heeft een kip? (2)',
        ],
        normaal: [
          'Ik ben een getal. Tel je mij bij mezelf op, dan krijg je 12. (6)',
          'Hoeveel poten hebben een paard en een kip samen? (6)',
          'Hoeveel poten hebben 2 eenden samen? (4)',
          'Het aantal letters in het woord WINDY. (5)',
          'Een hand heeft 5 vingers. Hoeveel vingers hebben 2 handen min 1? (9)',
          'Hoeveel hoeken heeft een driehoek plus een vierkant samen, gedeeld door 7? (1)',
        ],
        pittig: [
          'Welk cijfer komt na 1, 1, 2, 3, 5? (8)',
          'Ik ben oneven. Haal je een letter weg, dan word ik even. Welk getal? (7, zeven → even)',
          'Hoeveel keer kan je 5 aftrekken van 25? (1 keer: daarna is het 20)',
          'Een klok slaat 6 uur in 5 seconden. Hoe veel slagen zijn er? (6)',
          'Het aantal letters in DUVELKE min het aantal letters in KENZO. (2)',
          'Wat is de helft van 2 plus 2? (3)',
        ],
      },
      pick: 3,
      secret: true,
    },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Roep heel snel een fout cijfer en klink heel zeker.',
      'Verwar de volgorde van de cijfers een beetje.',
      'Twijfel luidop aan het juiste antwoord.',
    ],
    dilemma: true,
  },
  {
    id: 'raadseltijd',
    title: 'Windy’s raadselbox',
    emoji: '🤔',
    category: 'raadsels',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain: 'De spelleider leest de raadsels één voor één voor. Jullie krijgen één antwoord per raadsel. Hoeveel raden jullie er?',
    list: {
      title: 'Raadsels (antwoorden enkel voor de spelleider)',
      items: {
        makkelijk: [
          'Wat heeft tanden maar kan niet bijten? (een kam)',
          'Wat wordt natter hoe meer het droogt? (een handdoek)',
          'Wat heeft een nek maar geen hoofd? (een fles)',
          'Wat loopt maar heeft geen benen? (water, een neus, een klok)',
          'Wat heeft vier poten maar kan niet lopen? (een tafel of stoel)',
          'Wat is er altijd voor je, maar kan je nooit zien? (de toekomst)',
          'Welk dier draagt zijn huis op zijn rug? (een slak of schildpad)',
        ],
        normaal: [
          'Wat heeft toetsen maar kan geen deur openen? (een piano of toetsenbord)',
          'Hoe meer je ervan neemt, hoe meer je achterlaat. (voetstappen)',
          'Wat breekt als je het zegt? (stilte)',
          'Wat gaat omhoog maar nooit omlaag? (je leeftijd)',
          'Wat heeft steden maar geen huizen, bossen maar geen bomen? (een landkaart)',
          'Wat kan je vangen maar niet gooien? (een verkoudheid)',
          'Wat heeft een hoofd en een staart maar geen lijf? (een munt)',
        ],
        pittig: [
          'Ik spreek zonder mond en hoor zonder oren. Wat ben ik? (een echo)',
          'De vader van Emma heeft vijf dochters: Nana, Nene, Nini, Nono. Hoe heet de vijfde? (Emma)',
          'Wat is zwaarder: een kilo veren of een kilo stenen? (even zwaar)',
          'Wat kan je nooit eten als ontbijt? (middageten en avondeten)',
          'Hoe kan iemand acht dagen niet slapen? (hij slaapt ’s nachts)',
          'Wat komt één keer voor in een minuut, twee keer in een moment, maar nooit in duizend jaar? (de letter M)',
          'Wat wordt groter hoe meer je eruit weghaalt? (een gat)',
        ],
      },
      pick: 5,
      secret: true,
    },
    scoring: { type: 'aantal', target: 5, unit: 'raadsels' },
    sabotage: [
      'Zeg als eerste een fout antwoord en probeer de anderen te overtuigen.',
      'Maak veel lawaai als iemand het juiste antwoord wil zeggen.',
      'Zeg "dat kan niet kloppen" als iemand het goede antwoord geeft.',
    ],
  },

  // ─────────────── Samenwerken ───────────────
  {
    id: 'bekertoren',
    title: 'De bekertoren',
    emoji: '🥤',
    category: 'samenwerken',
    locations: ['binnen', 'tuin'],
    supplies: ['plastiekbekers'],
    minPlayers: 3,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Bouw samen een piramide van bekers met {lagen} lagen. Maar let op: iedereen mag maar één hand gebruiken, en je andere hand hou je op je rug!',
    vars: { lagen: { makkelijk: [3], normaal: [4], pittig: [5] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Zet je beker net niet helemaal recht.',
      'Geef enthousiast verkeerd bouwadvies.',
      'Adem "per ongeluk" net iets te hard als de toren bijna af is. Maar raak hem niet aan!',
    ],
    dilemma: true,
    photo: 'De toren met de bouwers eromheen.',
  },
  {
    id: 'tel-tot-twintig',
    title: 'Tel tot twintig',
    emoji: '🔢',
    category: 'samenwerken',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 5,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Ga in een kring staan en doe je ogen dicht. Tel samen tot {doel}, maar zonder af te spreken wie wat zegt. Iedereen mag op elk moment het volgende getal zeggen. Zeggen twee mensen tegelijk iets? Dan begin je opnieuw bij 1!',
    vars: { doel: { makkelijk: [12], normaal: [20], pittig: [25] } },
    scoring: { type: 'gelukt' },
    sabotage: [
      'Zeg soms een getal op hetzelfde moment als iemand anders.',
      'Wacht tot het net stil is en roep dan meteen, net te snel.',
      'Doe alsof je je vergist en zeg een getal dat al geweest is.',
    ],
  },
  {
    id: 'mensenknoop',
    title: 'De mensenknoop',
    emoji: '🪢',
    category: 'samenwerken',
    locations: OVERAL,
    supplies: [],
    minPlayers: 4,
    minutes: 6,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Ga in een kring staan, steek je handen in het midden en neem twee willekeurige handen vast (niet van je buren). Nu zitten jullie in de knoop! Ontwar de knoop tot een kring zonder los te laten. Rustig en voorzichtig: niemand mag pijn hebben.',
    scoring: { type: 'gelukt' },
    sabotage: [
      'Laat "per ongeluk" even los en doe alsof het niet opviel.',
      'Stel steeds een beweging voor die de knoop net erger maakt.',
      'Beweeg heel traag als iedereen snel wil.',
    ],
    photo: 'De knoop op het moeilijkste moment.',
  },
  {
    id: 'kranteneiland',
    title: 'Het kranteneiland',
    emoji: '📰',
    category: 'samenwerken',
    locations: ['binnen', 'tuin', 'park'],
    supplies: ['krantenpapier'],
    minPlayers: 3,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Leg een open krant op de grond. De hele groep moet erop staan, 5 tellen lang, zonder de grond te raken. Lukt het? Dan wordt de krant dubbelgevouwen. Hoeveel keer kunnen jullie de krant vouwen? Doel: {doel} keer.',
    vars: { doel: { makkelijk: [2], normaal: [3], pittig: [4] } },
    scoring: { type: 'aantal', target: '{doel}', unit: 'keer gevouwen' },
    sabotage: ['Zet stiekem je teen net naast de krant.', 'Stel voor om op één been te staan, net als het niet nodig is.', 'Giechel en wiebel.'],
    photo: 'Iedereen samen op het kleinste stukje krant.',
  },
  {
    id: 'tapijt-omdraaien',
    title: 'Het vliegende tapijt',
    emoji: '🧞',
    category: 'samenwerken',
    locations: ['binnen', 'tuin', 'park', 'strand'],
    supplies: ['handdoeken'],
    minPlayers: 3,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Iedereen gaat op een grote handdoek of deken staan: dat is jullie vliegende tapijt. Draai het tapijt helemaal om, zonder dat iemand de grond raakt!',
    scoring: { type: 'gelukt' },
    sabotage: ['Zet stiekem een voet naast het tapijt.', 'Ga net op het stuk staan dat omgedraaid moet worden.', 'Geef het tegenovergestelde advies van wat werkt.'],
    photo: 'Het tapijt halverwege het omdraaien.',
  },
  {
    id: 'hoepelketting',
    title: 'De hoepelketting',
    emoji: '⭕',
    category: 'samenwerken',
    locations: ['binnen', 'tuin', 'park', 'strand'],
    supplies: ['hoepels'],
    minPlayers: 4,
    minutes: 5,
    timer: 120,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Vorm een kring en geef elkaar een hand. De hoepel hangt over één paar armen. Laat de hoepel de hele kring rondgaan, over iedereen heen, zonder los te laten. Lukt het {rondes} keer rond binnen de tijd?',
    vars: { rondes: { makkelijk: [1], normaal: [2], pittig: [3] } },
    scoring: { type: 'aantal', target: '{rondes}', unit: 'rondes' },
    sabotage: ['Laat even los als niemand kijkt.', 'Ga heel stijf staan zodat de hoepel blijft haken.', 'Doe traag als de rest snel gaat.'],
  },

  // ─────────────── Geheugen ───────────────
  {
    id: 'dienblad',
    title: 'Het dienblad',
    emoji: '🧠',
    category: 'geheugen',
    locations: ['binnen', 'tuin'],
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Leg {aantal} verschillende voorwerpen uit huis op een dienblad of tafel en dek ze af met een doek.',
    explain:
      'Onder de doek liggen {aantal} voorwerpen. Jullie mogen 1 minuut kijken. Daarna draaien jullie je om en haalt de spelleider er één weg. Welk voorwerp is weg? Dat doen we 3 rondes.',
    vars: { aantal: { makkelijk: [8], normaal: [12], pittig: [16] } },
    scoring: { type: 'aantal', target: 3, unit: 'rondes juist' },
    sabotage: ['Roep snel een fout antwoord.', 'Twijfel luidop over het juiste antwoord.', 'Zeg dat je zeker weet dat een ander voorwerp er ook was.'],
  },
  {
    id: 'ik-ga-op-reis',
    title: 'Windy gaat op reis',
    emoji: '🧳',
    category: 'geheugen',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Windy gaat op reis en neemt mee... De eerste zegt: "Windy neemt haar pruik mee." De volgende herhaalt dat en voegt er iets aan toe. Zo gaat het rond. Hoe lang wordt de koffer? Doel: {doel} dingen zonder fout.',
    vars: { doel: { makkelijk: [8], normaal: [12], pittig: [16] } },
    scoring: { type: 'aantal', target: '{doel}', unit: 'dingen' },
    sabotage: ['Vergeet "per ongeluk" iets in het midden.', 'Voeg iets heel lang en moeilijks toe.', 'Wissel de volgorde van twee dingen.'],
  },
  {
    id: 'patroon',
    title: 'Het klappatroon',
    emoji: '👏',
    category: 'geheugen',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 5,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De spelleider doet een patroon voor met klappen, stampen en knippen. De hele groep doet het tegelijk na. Elke ronde wordt het langer. Hoeveel rondes lukken jullie? Doel: {doel}.',
    vars: { doel: { makkelijk: [4], normaal: [6], pittig: [8] } },
    scoring: { type: 'aantal', target: '{doel}', unit: 'rondes' },
    sabotage: ['Klap net een tel te vroeg, zodat anderen twijfelen.', 'Doe met veel zelfvertrouwen een fout patroon.', 'Tel luidop verkeerd mee.'],
  },

  // ─────────────── Behendigheid ───────────────
  {
    id: 'ballonnen-hooghouden',
    title: 'Ballonnen in de lucht',
    emoji: '🎈',
    category: 'behendigheid',
    locations: ['binnen', 'tuin'],
    supplies: ['ballonnen'],
    minPlayers: 3,
    minutes: 5,
    timer: 60,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Hou {aantal} ballonnen tegelijk in de lucht, een volle minuut lang. Niemand mag dezelfde ballon twee keer na elkaar aantikken. Valt er een ballon op de grond, dan is het mislukt!',
    vars: { aantal: { makkelijk: [2], normaal: [3], pittig: [4] } },
    scoring: { type: 'gelukt' },
    sabotage: ['Tik een ballon net iets te hard, richting een hoek.', 'Ga net in de weg staan als iemand wil tikken.', 'Roep "ik heb hem!" en laat hem dan toch gaan.'],
    photo: 'Iedereen springend naar een ballon.',
  },
  {
    id: 'lepelrace',
    title: 'De lepelrace',
    emoji: '🥄',
    category: 'behendigheid',
    locations: ['binnen', 'tuin', 'park'],
    supplies: ['lepels', 'tennisballen'],
    minPlayers: 3,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Estafette! Draag een tennisbal op een lepel naar de overkant en terug, en geef hem door. Valt de bal? Dan begin je opnieuw vanaf de start. Komt iedereen aan de beurt voor de tijd om is?',
    scoring: { type: 'gelukt' },
    sabotage: ['Wandel extra traag.', 'Laat de bal "per ongeluk" vallen, maar niet te vaak.', 'Geef de lepel onhandig door.'],
    photo: 'De concentratie van de lepelrace.',
  },
  {
    id: 'mikken-emmer',
    title: 'Mikken maar!',
    emoji: '🎯',
    category: 'behendigheid',
    locations: ['tuin', 'park', 'bos', 'strand'],
    supplies: ['emmers', 'tennisballen'],
    minPlayers: 3,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Zet de emmer op {afstand} grote stappen. Iedereen mag {worpen} keer gooien. Samen moeten jullie {doel} ballen in de emmer krijgen.',
    vars: {
      afstand: { makkelijk: [4], normaal: [6], pittig: [8] },
      worpen: { normaal: [3] },
      doel: { makkelijk: [4], normaal: [6], pittig: [8] },
    },
    scoring: { type: 'aantal', target: '{doel}', unit: 'ballen' },
    sabotage: ['Gooi net iets te ver of te kort.', 'Geef enthousiast verkeerd mikadvies.', 'Stoot "per ongeluk" tegen de emmer als je de ballen gaat halen.'],
  },
  {
    id: 'balcirkel',
    title: 'De balcirkel',
    emoji: '⚽',
    category: 'behendigheid',
    locations: RUSTIG_BUITEN,
    supplies: ['bal'],
    minPlayers: 3,
    minutes: 5,
    timer: 120,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Ga in een grote kring staan. Gooi de bal naar elkaar en roep telkens de naam van wie je gooit. Niet naar je buren! Valt de bal, dan begint het tellen opnieuw. Halen jullie {doel} worpen na elkaar?',
    vars: { doel: { makkelijk: [10], normaal: [20], pittig: [30] } },
    scoring: { type: 'gelukt' },
    sabotage: ['Roep een andere naam dan waar je naartoe gooit.', 'Gooi net iets te hoog.', 'Kijk weg als de bal naar je komt.'],
  },
  {
    id: 'papieren-vliegtuig',
    title: 'De vliegtuigfabriek',
    emoji: '✈️',
    category: 'behendigheid',
    locations: ['binnen', 'tuin'],
    supplies: ['papier'],
    minPlayers: 3,
    minutes: 8,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Iedereen vouwt een papieren vliegtuig. Daarna gooit iedereen om de beurt vanaf een lijn. Een vliegtuig telt als het verder dan {afstand} grote stappen landt. Doel: {doel} vliegtuigen.',
    vars: { afstand: { makkelijk: [3], normaal: [4], pittig: [5] }, doel: { makkelijk: [2], normaal: [3], pittig: [4] } },
    scoring: { type: 'aantal', target: '{doel}', unit: 'vliegtuigen' },
    sabotage: ['Vouw je vliegtuig net scheef.', 'Geef anderen een "handige" vouwtip die niet werkt.', 'Gooi naar beneden.'],
    photo: 'Alle vliegtuigen klaar voor vertrek.',
  },

  // ─────────────── Creatief ───────────────
  {
    id: 'uitbeelden',
    title: 'Uitbeelden',
    emoji: '🎭',
    category: 'creatief',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Eén iemand beeldt uit, zonder te praten of geluid te maken. De rest raadt. Is het geraden? Dan beeldt de volgende het volgende woord uit. Hoeveel woorden raden jullie voor de tijd om is?',
    roles: [{ name: 'Eerste uitbeelder', count: 1, hint: 'Bekijk het eerste woord stiekem op de tablet.' }],
    list: {
      title: 'Uitbeeldwoorden',
      items: {
        makkelijk: ['olifant', 'tandenpoetsen', 'fietsen', 'kikker', 'zwemmen', 'slapen', 'voetbal', 'ijsje eten', 'vliegtuig', 'hond', 'aap', 'dansen'],
        normaal: ['astronaut', 'pannenkoeken bakken', 'brandweerman', 'pinguïn', 'skiën', 'tandarts', 'een ballon opblazen', 'kapper', 'koe melken', 'surfen', 'dinosaurus', 'selfie nemen', 'regen', 'schaatsen', 'piraat'],
        pittig: ['vulkaan', 'onweer', 'bakker die zich verbrandt', 'spin in een web', 'windmolen', 'lift die vastzit', 'kampvuur', 'verliefd zijn', 'wasmachine', 'toverstaf', 'Windy haar pruik', 'jaloers zijn', 'kermis'],
      },
      pick: 10,
      secret: true,
    },
    scoring: { type: 'aantal', target: 6, unit: 'woorden' },
    sabotage: ['Raad expres een paar keer fout, maar met veel enthousiasme.', 'Beeld zelf onduidelijk uit.', 'Roep heel veel antwoorden door elkaar zodat niemand de juiste hoort.'],
    photo: 'De grappigste uitbeelding.',
  },
  {
    id: 'blind-tekenen',
    title: 'Blind tekenen',
    emoji: '✏️',
    category: 'creatief',
    locations: ['binnen', 'tuin'],
    supplies: ['papier', 'stiften'],
    minPlayers: 3,
    minutes: 8,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De Verteller leest stiekem een tekening op de tablet en legt uit wat de anderen moeten tekenen, zonder de naam van het ding te zeggen. De tekenaars mogen niets vragen! Daarna vergelijken jullie. Lijkt het genoeg? Dan is het gelukt.',
    roles: [{ name: 'Verteller', count: 1, hint: 'Lees de tekening stiekem op de tablet.' }],
    list: {
      title: 'Wat moeten ze tekenen?',
      items: {
        makkelijk: ['Een huis met een rode deur, twee ramen en een zon linksboven.', 'Een grote boom met drie appels en een vogel ernaast.', 'Een smiley met een hoed.'],
        normaal: ['Een huis met een schoorsteen die rookt, een boom rechts en een wolk boven het huis.', 'Een kat die op een stoel zit, met een bal onder de stoel.', 'Een raket met drie ramen die naar de maan vliegt.'],
        pittig: ['Een zeilboot op golven, met een zon half achter een wolk en een vis die uit het water springt.', 'Windy met haar pruik, die met haar ene hand zwaait en met de andere een pannenkoek vasthoudt.', 'Een kasteel met twee torens, een vlag op de linkertoren en een brug over een gracht.'],
      },
      pick: 1,
      secret: true,
    },
    scoring: { type: 'gelukt' },
    sabotage: ['Als Verteller: zeg links en rechts eens verkeerd om.', 'Teken zelf heel klein in een hoekje.', 'Voeg stiekem iets toe dat er niet bij hoort.'],
    photo: 'Alle tekeningen naast elkaar.',
  },
  {
    id: 'rijmrap',
    title: 'De Windy-rap',
    emoji: '🎤',
    category: 'creatief',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Maak samen een rap van {regels} zinnen over {onderwerp}. De zinnen moeten rijmen! Daarna voeren jullie hem op voor de spelleider, met beat (klappen of stampen).',
    vars: {
      regels: { makkelijk: [2], normaal: [4], pittig: [6] },
      onderwerp: { normaal: ['de jarige', 'Windy haar pruik', 'onzen Kenzo', "'t Duvelke", 'pannenkoeken', 'de schatkist'] },
    },
    scoring: { type: 'gelukt' },
    sabotage: ['Stel woorden voor die op niets rijmen.', 'Vergeet je zin op het moment van optreden.', 'Klap uit de maat.'],
    photo: 'De rappers in hun stoerste pose.',
  },
  {
    id: 'stoepkrijt-kunst',
    title: 'Het krijtkunstwerk',
    emoji: '🖍️',
    category: 'creatief',
    locations: ['straat', 'tuin', 'park'],
    supplies: ['stoepkrijt'],
    minPlayers: 3,
    minutes: 10,
    timer: 360,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Teken samen één groot kunstwerk met stoepkrijt over het thema "{thema}". Het moet minstens deze dingen bevatten: {dingen}. Enkel op de stoep of het terras, nooit op de rijweg!',
    vars: {
      thema: { normaal: ['een schattenjacht', 'de verjaardag', 'de onderwaterwereld', 'Windy’s droomhuis', 'de ruimte'] },
      dingen: { makkelijk: ['een zon, een dier en een hart'], normaal: ['een zon, drie dieren, een schatkist en iedereens naam'], pittig: ['een zon, vijf dieren, een schatkist, een geheime code en iedereens handtekening'] },
    },
    scoring: { type: 'gelukt' },
    sabotage: ['Teken iets dat helemaal niet bij het thema past.', 'Neem veel tijd voor je eigen stukje.', 'Vergeet "per ongeluk" één van de verplichte dingen.'],
    photo: 'Het kunstwerk van bovenaf.',
  },
  {
    id: 'zandkasteel',
    title: 'Het zandkasteel',
    emoji: '🏰',
    category: 'creatief',
    locations: ['strand'],
    supplies: ['schepjes', 'emmers'],
    minPlayers: 3,
    minutes: 12,
    timer: 480,
    difficulties: [...ALLE_NIVEAUS],
    explain: 'Bouw samen een kasteel met {torens} torens, een gracht en een poort. Het moet nog rechtstaan als de tijd om is!',
    vars: { torens: { makkelijk: [2], normaal: [4], pittig: [6] } },
    scoring: { type: 'gelukt' },
    sabotage: ['Graaf de gracht net te dicht bij een toren.', 'Gebruik droog zand voor jouw toren.', 'Stel voor om het kasteel steeds groter te maken.'],
    photo: 'De bouwers achter hun kasteel.',
  },

  // ─────────────── Quiz ───────────────
  {
    id: 'windy-quiz',
    title: 'Windy’s superquiz',
    emoji: '❓',
    category: 'quiz',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Windy stelt {aantal} vragen. Overleg samen en kies één antwoord. De tablet telt zelf de punten. Maar pas op: wie hard roept, heeft niet altijd gelijk!',
    vars: { aantal: { normaal: [8] } },
    scoring: { type: 'quiz', questions: 8 },
    sabotage: ['Roep heel zeker een fout antwoord.', 'Zeg "dat weet ik uit school!" bij een fout antwoord.', 'Tik snel op een antwoord voor de anderen klaar zijn met overleggen, maar enkel als jij de tablet vasthoudt.'],
  },
  {
    id: 'dieren-alfabet',
    title: 'Het dierenalfabet',
    emoji: '🦒',
    category: 'quiz',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 5,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Noem om de beurt een dier, in volgorde van het alfabet: A van aap, B van beer... Weet je het niet, dan mag de groep helpen. Hoe ver komen jullie? Doel: letter {letter}.',
    vars: { letter: { makkelijk: ['K'], normaal: ['P'], pittig: ['W'] } },
    scoring: { type: 'gelukt' },
    sabotage: ['Denk heel lang na, ook als je het weet.', 'Noem een dier met de verkeerde letter en hou vol dat het klopt.', 'Leid de anderen af met grapjes.'],
  },
  {
    id: 'woordslang',
    title: 'De woordslang',
    emoji: '🐍',
    category: 'quiz',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 5,
    timer: 120,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Zeg om de beurt een woord uit het thema "{thema}". Je woord moet beginnen met de laatste letter van het vorige woord. Geen dubbels! Hoeveel woorden halen jullie? Doel: {doel}.',
    vars: {
      thema: { makkelijk: ['eten'], normaal: ['dieren', 'eten', 'dingen in huis'], pittig: ['landen en steden', 'beroepen'] },
      doel: { makkelijk: [8], normaal: [12], pittig: [15] },
    },
    scoring: { type: 'aantal', target: '{doel}', unit: 'woorden' },
    sabotage: ['Zeg een woord dat al gezegd is.', 'Kies een woord dat eindigt op een moeilijke letter (zoals x of q).', 'Neem veel bedenktijd.'],
  },

  // ─────────────── Communicatie ───────────────
  {
    id: 'blinde-piloot',
    title: 'De blinde piloot',
    emoji: '🙈',
    category: 'communicatie',
    locations: ['binnen', 'tuin', 'park'],
    supplies: ['blinddoek', 'knuffels'],
    minPlayers: 3,
    minutes: 7,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Leg een knuffel ergens in de ruimte, op een veilige plek zonder trappen of scherpe hoeken.',
    explain:
      'De Piloot krijgt een blinddoek. De rest mag enkel met woorden de weg wijzen naar de knuffel: vooruit, stop, links, rechts. Niemand mag de Piloot aanraken. Brengt de Piloot de knuffel terug naar de start? Voorzichtig en traag!',
    roles: [{ name: 'Piloot', count: 1, hint: 'Doe de blinddoek om.' }],
    scoring: { type: 'gelukt' },
    sabotage: ['Zeg één keer links als het rechts moet zijn, en verbeter je daarna snel.', 'Praat net door iemand anders heen.', 'Zeg "nog een beetje" als de Piloot er al is.'],
    photo: 'De piloot met blinddoek en de knuffel.',
  },
  {
    id: 'fluisterketting',
    title: 'De fluisterketting',
    emoji: '👂',
    category: 'communicatie',
    locations: OVERAL,
    supplies: [],
    minPlayers: 4,
    minutes: 6,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De Eerste leest stiekem een zin op de tablet en fluistert die in het oor van de volgende. Zo gaat het rij rond. De laatste zegt de zin luidop. Is hij bijna hetzelfde? Dan is het gelukt. We doen 3 zinnen.',
    roles: [{ name: 'Eerste', count: 1, hint: 'Lees de zin stiekem op de tablet.' }],
    list: {
      title: 'Fluisterzinnen',
      items: {
        makkelijk: ['Windy eet graag pannenkoeken.', 'De kat zit op het dak.', 'Kenzo slaapt nog.', 'Mijn pruik is zwart.'],
        normaal: ['Windy heeft haar pruik in de soep laten vallen.', 'Onzen Kenzo heeft zeven sokken onder zijn bed.', 'De buurvrouw weet altijd alles eerst.', 'Een giraf met een sjaal eet een ijsje.'],
        pittig: ['Zeven zotte zeehonden zwemmen zingend naar Zeeland.', 'Windy’s buurvrouw bakt bruine broodjes met blauwe bessen.', 'Kenzo kocht krokante koekjes in de Kempen.', 'Achtentachtig acrobaten aten appeltaart.'],
      },
      pick: 3,
      secret: true,
    },
    scoring: { type: 'aantal', target: 3, unit: 'zinnen' },
    sabotage: ['Verander één woord een beetje als je doorfluistert.', 'Fluister heel zacht of heel snel.', 'Doe alsof je het niet goed verstaan hebt.'],
  },
  {
    id: 'blind-bouwen',
    title: 'De bouwmeester',
    emoji: '🧱',
    category: 'communicatie',
    locations: ['binnen'],
    supplies: ['legoblokjes'],
    minPlayers: 3,
    minutes: 8,
    timer: 240,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Bouw in het geheim een klein bouwwerkje van {blokjes} blokjes en zet het uit het zicht. Leg dezelfde blokjes klaar voor de groep.',
    explain:
      'De Bouwmeester mag het geheime bouwwerk gaan bekijken, maar niet aanraken. Daarna legt de Bouwmeester uit hoe de rest het moet nabouwen, zonder zelf blokjes aan te raken. Lijkt het precies? Dan is het gelukt.',
    vars: { blokjes: { makkelijk: [5], normaal: [8], pittig: [12] } },
    roles: [{ name: 'Bouwmeester', count: 1, hint: 'Ga het geheime bouwwerk bekijken.' }],
    scoring: { type: 'gelukt' },
    sabotage: ['Als Bouwmeester: zeg een kleur verkeerd.', 'Bouw jouw stukje net verkeerd om.', 'Stel veel vragen door elkaar.'],
    photo: 'Het origineel naast de kopie.',
  },

  // ─────────────── Tijdsdruk ───────────────
  {
    id: 'sokkenchaos',
    title: 'Sokkenchaos',
    emoji: '🧦',
    category: 'tijdsdruk',
    locations: ['binnen'],
    supplies: ['sokken', 'wasmand'],
    minPlayers: 3,
    minutes: 5,
    timer: 90,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Gooi {paren} paar sokken door elkaar in een wasmand.',
    explain: 'Oei, de was van onzen Kenzo! Zoek zo snel mogelijk alle {paren} paren sokken bij elkaar en rol ze op.',
    vars: { paren: { makkelijk: [6], normaal: [10], pittig: [14] } },
    scoring: { type: 'aantal', target: '{paren}', unit: 'paren' },
    sabotage: ['Maak een paar met twee sokken die net niet hetzelfde zijn.', 'Rol een sok op zonder partner.', 'Verstop een sok onder de mand.'],
    photo: 'De stapel opgerolde sokken.',
  },
  {
    id: 'tijdbom',
    title: 'De tijdbom',
    emoji: '💣',
    category: 'tijdsdruk',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 6,
    timer: 60,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De tijdbom tikt! Noem samen binnen de minuut {doel} dingen die {soort}. De spelleider telt mee. Dubbels tellen niet!',
    vars: {
      doel: { makkelijk: [8], normaal: [12], pittig: [15] },
      soort: { normaal: ['geel zijn', 'in de keuken liggen', 'kunnen vliegen', 'je op een verjaardagsfeest vindt', 'rond zijn', 'in de zee leven'] },
    },
    scoring: { type: 'aantal', target: '{doel}', unit: 'dingen' },
    sabotage: ['Herhaal iets dat al gezegd is.', 'Zeg iets dat er net niet bij hoort.', 'Praat door de anderen heen.'],
  },
  {
    id: 'innerlijke-klok',
    title: 'De innerlijke klok',
    emoji: '⏱️',
    category: 'tijdsdruk',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 4,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Iedereen doet de ogen dicht. De spelleider start de klok. Roep samen "STOP!" als jullie denken dat er precies {seconden} seconden voorbij zijn. Niet luidop tellen! Zitten jullie er minder dan {marge} seconden naast, dan is het gelukt.',
    vars: { seconden: { makkelijk: [20], normaal: [30], pittig: [45] }, marge: { makkelijk: [4], normaal: [3], pittig: [2] } },
    scoring: { type: 'stopwatch', seconds: '{seconden}', margin: '{marge}' },
    sabotage: ['Roep net iets te vroeg "stop".', 'Tel zachtjes verkeerd, net hoorbaar voor je buur.', 'Zeg dat het "zeker al tijd is".'],
  },

  // ─────────────── Speuren ───────────────
  {
    id: 'wat-is-veranderd',
    title: 'Wat is er veranderd?',
    emoji: '🕵️',
    category: 'speuren',
    locations: OVERAL,
    supplies: [],
    minPlayers: 4,
    minutes: 7,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De Detective kijkt 30 seconden goed naar de groep. Dan gaat de Detective even weg. De groep verandert {aantal} dingen aan zichzelf (bril af, mouw opgerold, plaats gewisseld). Vindt de Detective alle veranderingen?',
    vars: { aantal: { makkelijk: [2], normaal: [3], pittig: [5] } },
    roles: [{ name: 'Detective', count: 1, hint: 'Kijk goed naar iedereen.' }],
    scoring: { type: 'gelukt' },
    sabotage: ['Verander iets heel kleins dat bijna niet op te merken is.', 'Verander stiekem nog iets extra, zodat het meer wordt dan afgesproken.', 'Geef de Detective een verkeerde hint.'],
  },
  {
    id: 'geluiden-raden',
    title: 'Wat hoor je?',
    emoji: '🔊',
    category: 'speuren',
    locations: ['binnen'],
    supplies: [],
    minPlayers: 3,
    minutes: 7,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Zoek {aantal} voorwerpen die een geluid maken (sleutelbos, papier verfrommelen, lepel in een tas, rits...).',
    explain: 'Iedereen doet de ogen dicht. De spelleider maakt {aantal} geluiden. Overleg na elk geluid: wat was het? Doel: {doel} juist.',
    vars: { aantal: { normaal: [7] }, doel: { makkelijk: [4], normaal: [5], pittig: [6] } },
    scoring: { type: 'aantal', target: '{doel}', unit: 'geluiden' },
    sabotage: ['Roep snel een fout antwoord en klink heel zeker.', 'Maak zelf een beetje geluid zodat het moeilijker te horen is.', 'Zeg "dat hebben we al gehad".'],
  },
  {
    id: 'spoorzoeker',
    title: 'De spoorzoeker',
    emoji: '👣',
    category: 'speuren',
    locations: ['tuin', 'bos', 'park'],
    supplies: ['wol'],
    minPlayers: 3,
    minutes: 10,
    timer: 420,
    difficulties: [...ALLE_NIVEAUS],
    prep: 'Knoop op voorhand {aantal} stukjes wol aan takken of struiken langs een route, en verstop op het einde een kleine verrassing.',
    explain: 'Volg het spoor van gekleurde wolletjes. Tel ze onderweg! Aan het einde vinden jullie iets. Vertel de spelleider hoeveel wolletjes er waren.',
    vars: { aantal: { makkelijk: [6], normaal: [10], pittig: [14] } },
    scoring: { type: 'gelukt' },
    sabotage: ['Tel luidop verkeerd.', 'Zeg dat je een wolletje ziet in de verkeerde richting.', 'Neem een wolletje stiekem mee in je zak.'],
    photo: 'De ontdekkingsreizigers bij de verrassing.',
  },

  // ─────────────── Foto ───────────────
  {
    id: 'fotoposes',
    title: 'Poseer als...',
    emoji: '📸',
    category: 'foto',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De spelleider noemt een pose. De hele groep heeft 10 tellen om samen die pose te vormen, zonder te praten! Dan maakt de spelleider een foto. Staat iedereen goed? Dan telt het.',
    list: {
      title: 'Poses',
      items: {
        normaal: ['een brug', 'een grote bloem', 'een auto met vier wielen', 'een verjaardagstaart', 'een draak', 'de letter H', 'een wasmachine', 'Windy haar pruik', 'een raket die opstijgt', 'een spin'],
      },
      pick: 5,
      secret: false,
    },
    scoring: { type: 'aantal', target: 5, unit: 'poses' },
    sabotage: ['Doe iets totaal anders dan de rest.', 'Beweeg net als de foto genomen wordt.', 'Lach zo hard dat anderen ook moeten lachen.'],
    photo: 'De beste pose van allemaal.',
  },
  {
    id: 'reuzenwoord',
    title: 'Het reuzenwoord',
    emoji: '✍️',
    category: 'foto',
    locations: ['tuin', 'bos', 'park', 'strand'],
    supplies: [],
    minPlayers: 3,
    minutes: 8,
    timer: 300,
    difficulties: [...ALLE_NIVEAUS],
    explain: 'Schrijf het woord "{woord}" zo groot mogelijk op de grond met takjes, blaadjes, steentjes of schelpen. Elke letter minstens zo groot als een voet!',
    vars: { woord: { makkelijk: ['WINDY', 'FEEST'], normaal: ['DUVELKE', 'SCHATKIST'], pittig: ['VERJAARDAG', 'SPEURNEUS'] } },
    scoring: { type: 'gelukt' },
    sabotage: ['Maak jouw letter spiegelverkeerd.', 'Gebruik te weinig spullen voor jouw letter.', 'Vergeet een letter in het midden.'],
    photo: 'Het reuzenwoord van bovenaf, met iedereen erachter.',
  },

  // ─────────────── Beweging ───────────────
  {
    id: 'standbeelden',
    title: 'Windy’s standbeelden',
    emoji: '🗿',
    category: 'beweging',
    locations: OVERAL,
    supplies: [],
    minPlayers: 3,
    minutes: 5,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'De spelleider draait zich om en telt tot {tellen}. Dan mag iedereen bewegen, dansen of sluipen. Draait de spelleider zich om, dan moet iedereen stokstijf stilstaan. Wie beweegt, moet terug naar de start. Tikt iemand de spelleider aan binnen {rondes} rondes? Dan is het gelukt.',
    vars: { tellen: { normaal: [5] }, rondes: { makkelijk: [8], normaal: [6], pittig: [5] } },
    scoring: { type: 'gelukt' },
    sabotage: ['Beweeg "per ongeluk" net na het omdraaien.', 'Maak anderen aan het lachen als ze stil moeten staan.', 'Sluip extra traag.'],
  },
  {
    id: 'estafette-letters',
    title: 'Letterestafette',
    emoji: '🏃',
    category: 'beweging',
    locations: ['tuin', 'park', 'strand'],
    supplies: [],
    minPlayers: 3,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Markeer een start en een keerpunt op {afstand} grote stappen. Loop om de beurt naar het keerpunt en roep daar een woord met de letter "{letter}". Terug, tik de volgende aan. Geen dubbele woorden! Halen jullie {doel} woorden voor de tijd om is?',
    vars: {
      afstand: { makkelijk: [8], normaal: [10], pittig: [12] },
      letter: { normaal: ['B', 'K', 'S', 'P', 'M', 'T'] },
      doel: { makkelijk: [6], normaal: [10], pittig: [14] },
    },
    scoring: { type: 'aantal', target: '{doel}', unit: 'woorden' },
    sabotage: ['Vergeet onderweg je woord en roep "euh...".', 'Zeg een woord dat al gezegd is.', 'Loop net iets trager.'],
  },
  {
    id: 'springtouw-samen',
    title: 'Samen springen',
    emoji: '🪢',
    category: 'beweging',
    locations: ['tuin', 'park', 'strand'],
    supplies: ['springtouw'],
    minPlayers: 4,
    minutes: 6,
    timer: 180,
    difficulties: [...ALLE_NIVEAUS],
    explain:
      'Twee mensen draaien het touw. De rest springt erin, één voor één, tot jullie met {springers} tegelijk springen. Houden jullie het {sprongen} sprongen vol?',
    vars: { springers: { makkelijk: [2], normaal: [3], pittig: [4] }, sprongen: { makkelijk: [3], normaal: [5], pittig: [8] } },
    roles: [{ name: 'Draaier', count: 2, hint: 'Draai het touw rustig en gelijk.' }],
    scoring: { type: 'gelukt' },
    sabotage: ['Draai het touw net iets te snel of te traag.', 'Spring net iets te laat in.', 'Roep "nu!" op het verkeerde moment.'],
    photo: 'Iedereen tegelijk in de lucht.',
  },
];
